cornell-dti/samwise

- frontend/src/components/FocusView/editTask.jsx
- frontend/src/components/FocusView/focusView.css
- frontend/src/components/FocusView/subtaskBox.jsx
- frontend/src/components/FocusView/taskBox.jsx
- frontend/src/store/actions.js
- frontend/src/store/reducers.js
Can add subtasks from focus view and mark as complete.  Checking off main task also marks all subtasks as complete.
> Subtask work

- frontend/src/components/FocusView/subtaskBox.jsx
removed console log when marking subtask as complete
> removed console log

- frontend/src/components/Backlog/Backlog.jsx
- frontend/src/components/Backlog/BacklogSubTask.jsx
- frontend/src/components/Backlog/BacklogTask.css
- frontend/src/components/Backlog/BacklogTask.jsx
- frontend/src/components/Backlog/backlog-types.js
- frontend/src/components/PopupTaskEditor/PopupInternalMainTaskEditor.jsx
- frontend/src/components/PopupTaskEditor/PopupInternalSubTaskEditor.jsx
- frontend/src/components/PopupTaskEditor/PopupTaskEditor.css
- frontend/src/components/PopupTaskEditor/PopupTaskEditor.jsx
- frontend/src/components/TagColorConfigEditor/TagColorConfigItemAdder.jsx
- frontend/src/store/action-types.js
- frontend/src/store/actions.js
- frontend/src/store/reducers.js
- frontend/src/store/store-types.js
- frontend/webpack.config.js
Outcome: Implemented a popup task editor that can easily used in other components.
Usage:
`<PopupTaskEditor {...task} />`
Example: This is already embed in the Backlog component. You can click the edit icon to see its effect.
Drawback: Currently the tag picker is not very well styled. It may require some cooperation from Michael to fully factor out his tag picker.
> Finished Feature: Edit Task

- .gitignore
- frontend/package.json
- frontend/src/components/TitleBar/Tags/TagAdder.css
Added CSS to fix the search box background
Also updated react search dependency in package.json
> Fixed some CSS weirdness

- backend/app/api/views.py
- frontend/public/index.html
- frontend/src/components/TitleBar/Tags/ClassTagAdder.jsx
- frontend/src/http/backend-adapter.js
- frontend/src/http/http-service.js
- frontend/src/store/action-types.js
- frontend/src/store/actions.js
- frontend/src/store/reducers.js
- frontend/src/store/store-types.js
- frontend/src/store/store.js
- frontend/src/util/tag-util.js
- frontend/webpack.config.js
- Removing a tag now makes all the tasks to that tag to have a new 'None' tag.
- Search box works now. Better searching algorithm config set.
- Updated Backend Endpoints Documentations: https://samwise.docs.apiary.io/
> Search import classes bugfixes

- frontend/src/components/TaskView/FutureView/FutureViewTask.jsx
- frontend/src/components/Util/TaskEditors/TaskEditor.jsx
Fix the condition to check whether a task is overdue.
Previous version will still report overdue when it's completed.
This version fixed it.
> Fix overdue check condition

- frontend/src/components/TitleBar/Tags/ClassTagAdder.jsx
- frontend/src/store/store.js
Fix the wrong caching behavior for searchbox using React.memo.
> Use React.memo instead of the naive cache.

- Dockerfile
- backend/app/api/views.py
- frontend/src/components/Util/Login/LoginBarrier.jsx
- frontend/src/util/firebase-util.js
The pull request fixed issue #48 and factored out some common backend code to make it more maintainable.
> Enforced cornell email and backend cleanup

- README.md
- docs/design-docs.md
- docs/flow-guide.md
- docs/style-guide.md
- frontend/.flowconfig
The README has been updated to present the most recent information. The names of the new members are deliberately excluded to leave it as an onboarding pull-request exercise for them.
I also added some style guide to address to the large influx of clean-code/code-style problems (Relevant ones: #65, #70, #71, #75). We need to follow these guides to improve the code quality. These guides also include some useful guides and links about how to install and configure various tools.
> Updated README and added style guide

- frontend/package.json
- frontend/src/components/TaskView/FutureView/FutureView.jsx
- frontend/src/components/TaskView/FutureView/FutureViewTask.jsx
- frontend/src/components/TaskView/TaskView.jsx
- frontend/src/components/TitleBar/Onboarding/Onboard.jsx
- frontend/src/components/TitleBar/Tags/TagItem.jsx
- frontend/src/components/UI/OverdueAlert.jsx
- frontend/src/components/UI/UndoToast.jsx
- frontend/src/components/Util/Login/LoginBarrier.jsx
- frontend/src/components/Util/Responsive/WindowSizeConsumer.jsx
- frontend/src/components/Util/TagListPicker/TagPickerItem.jsx
- frontend/src/components/Util/TaskEditors/InlineTaskEditor.jsx
- frontend/src/components/Util/TaskEditors/TaskEditor.jsx
- frontend/src/http/backend-adapter.js
- frontend/src/store/action-types.js
- frontend/src/store/actions.js
- frontend/src/store/react-redux-util.js
- frontend/src/store/reducers.js
- frontend/src/store/store.js
- frontend/src/util/datetime-util.js
- frontend/src/util/tag-util.js
- frontend/src/util/task-util.js
- frontend/src/util/toast-util.js
Addressed the problems raised in #65 #69 #70 #71 #73 #75. Also fixed a lot of linter and type errors in [Onboard component](https://github.com/cornell-dti/samwise/blob/master/frontend/src/components/TitleBar/Onboarding/Onboard.jsx).
> Code style fix

- frontend/src/components/ProgressTracker/ProgressTracker.css
- frontend/src/components/TaskCreator/TagPicker.jsx
- frontend/src/components/TaskCreator/TaskCreator.jsx
- frontend/src/components/TaskView/TaskView.css
- frontend/src/components/TitleBar/Onboarding/Onboard.css
- frontend/src/components/TitleBar/Onboarding/Onboard.jsx
- frontend/src/components/TitleBar/Tags/ColorEditor.jsx
- frontend/src/components/TitleBar/Tags/ListColors.js
Fixed styles in Onboarding, along with a few other small cleanup tasks.
> Frontend cleanup

- README.md
Fixed errors include:
- Incorrect Header Level
- Extra `)`
- Other markdown linter errors
> Fixed some awkward formatting mistake in README

- README.md
> Put my name in

- frontend/src/components/TaskCreator/TaskCreator.css
> Fix Box Shadow

- README.md
- docs/README.md
- docs/design-docs.md
- Fixed some links in top-level README
- Added actual content to design docs file.
> Added design docs about our current architecture

- frontend/.firebaserc
- frontend/package.json
- frontend/src/firebase/index.js
- frontend/webpack.stage.js
Separated staging environment and production environment in webpack. It allows us to easily use the staging environments to test our production-ready build.
> Separate Stage and Production in Webpack

- frontend/package.json
- frontend/src/index.jsx
- frontend/src/util/ga-util.js
Added Google Analytics. Enabled only for production environment.
> Added Google Analytics

- functions/src/index.ts
- functions/src/types.ts
The pull request #116 changes the db structure. This pull request updates the firebase functions to make it gather accurate data again.
> Fix analytics functions after db structure update

- frontend/src/components/TitleBar/Settings/SettingsPage.jsx
- frontend/src/components/TitleBar/TitleBar.css
- frontend/src/index.non-module.css
> V1 feedback fix sam

- frontend/src/assets/svgs/settings.svg
- frontend/src/components/TitleBar/Settings/SettingsButton.css
- frontend/src/components/TitleBar/Settings/SettingsButton.jsx
> made settings button 17.5px

- frontend/.flowconfig
- frontend/src/components/ProgressTracker/ProgressIndicator.css
- frontend/src/components/TaskCreator/DatePicker.jsx
- frontend/src/components/TaskCreator/Picker.css
- frontend/src/components/TaskCreator/TaskCreator.css
- frontend/src/components/Util/TagListPicker/TagListPicker.css
- frontend/src/components/Util/TagListPicker/TagListPicker.jsx
- frontend/src/components/Util/TaskEditors/TaskEditor/NewSubTaskEditor.jsx
Implemented designs for tag picker and calendar on Zeplin. Also updated progress bar animation to longer longer distort at and around 0%.
> Fix add task styling

- frontend/src/components/TaskView/FutureView/FutureViewControl.tsx
- frontend/src/components/TaskView/FutureView/FutureViewSevenColumns.css
- frontend/src/components/TaskView/FutureView/index.tsx
- frontend/src/components/TaskView/TaskView.css
- frontend/src/components/TaskView/index.tsx
Changes:
- task view has more horizontal margin
- mobile view of monthly/biweekly view is partially fixed given that the progress bar stays on the bottom
> Make more margin for task view and partially fix mobile view

- frontend/src/components/TaskView/FocusView/CompletedSeparator.module.css
- frontend/src/components/TaskView/FocusView/CompletedSeparator.tsx
- frontend/src/components/TaskView/FocusView/FocusTask.tsx
- frontend/src/components/TaskView/FocusView/FocusView.css
- frontend/src/components/TaskView/FocusView/index.tsx
- frontend/src/components/TaskView/FutureView/FutureViewControl.tsx
- frontend/src/components/TaskView/FutureView/FutureViewSevenColumns.css
- frontend/src/components/TaskView/FutureView/index.tsx
- frontend/src/components/TaskView/TaskView.css
- frontend/src/components/TaskView/index.tsx
- frontend/src/store/selectors.ts
- frontend/src/util/task-util.ts
Changes:
- Fixed the incorrect ordering bug (Fix #154)
- Separate complete from incomplete tasks in focus view to stick to the design (Fix #160)
- Also fixed progress bar computation error (Fix #171)
**Note**: please approve #172 first.
> Add completed focused section

- frontend/.eslintrc
- frontend/jest.config.js
- frontend/package.json
- frontend/src/components/UI/CheckBox.test.tsx
- frontend/src/components/UI/CheckBox.tsx
- frontend/src/components/UI/Loading.test.tsx
- frontend/src/util/datetime-util.test.ts
- frontend/webpack.common.js
- frontend/webpack.dev.js
- frontend/webpack.prod.js
- frontend/webpack.stage.js
This pull requests added [Jest](https://jestjs.io/) as a new dependency to test some of our utility functions and components.
Simple examples are added to illustrate how we can use Jest.
It also added the lint script to package.json
> Add jest test

- frontend/src/components/TaskView/FocusView/FocusTask.tsx
- frontend/src/components/TaskView/FocusView/FocusView.css
- frontend/src/components/TaskView/FocusView/index.tsx
- frontend/src/components/TaskView/FutureView/FutureViewNDays.css
- frontend/src/components/TaskView/FutureView/FutureViewSevenColumns.css
- frontend/src/components/TaskView/TaskView.css
- frontend/src/components/TaskView/index.tsx
- frontend/src/components/TitleBar/Banner/messages.ts
- frontend/src/components/Util/TaskEditors/InlineTaskEditor.tsx
- frontend/src/components/Util/TaskEditors/TaskEditor/EditorHeader.tsx
- frontend/src/components/Util/TaskEditors/TaskEditor/TaskEditor.css
- frontend/src/components/Util/TaskEditors/TaskEditor/index.tsx
- frontend/src/firebase/actions.ts
- frontend/src/store/selectors.ts
- frontend/src/util/task-util.test.ts
- frontend/src/util/task-util.ts
> Focus view enhancements

- frontend/src/components/TaskView/FutureView/FutureViewNDays.tsx
- frontend/src/components/TaskView/FutureView/FutureViewTask.css
- frontend/src/components/TaskView/FutureView/FutureViewTask.tsx
Added a JS expression to fix the long task bug
Made it so that the FutureViewNDays is dynamic with the number of days while still allowing long tasks
> Long task bug

- frontend/src/components/TaskView/README.md
- frontend/src/components/Util/AppInit/README.md
- frontend/src/components/Util/ErrorBoundary/README.md
- frontend/src/components/Util/TaskEditors/README.md
- frontend/src/components/Util/TaskEditors/TaskEditor/README.md
- frontend/src/components/Util/TaskEditors/TaskEditor/index.tsx
Added docs for some tricky components:
- TaskView
- LoginBarrier
- ErrorBoundary
- TaskEditors
- TaskEditor
- FloatingTaskEditor
- InlineTaskEditor
> Improve in-code docs

- admin-scripts/analytics.py
certain fields will need to be added to the tasks in the database in order for functions to work. For example, "dateCompleted" needs to be added in order to return "time saved" by the user.
> added 3 analytics functions

- frontend/src/components/TaskCreator/index.tsx
Enable pressing tab to exit again
> fix task creator a11y regression

- frontend/src/components/TitleBar/Settings/SettingsButton.module.css
- frontend/src/components/TitleBar/Settings/SettingsButton.tsx
- frontend/src/components/TitleBar/Tags/TagItem.module.css
Made focus/hover effects on settingspage consistent with those on main page
> SettingsPage Delete Button

- frontend/src/components/TaskCreator/DatePicker.tsx
- frontend/src/components/TaskCreator/Picker.module.css
- frontend/src/components/TaskCreator/index.tsx
Nonfunctional, based on preliminary zeplin designs.
> Repeat task gui

- admin-scripts/analytics.py
I added docstrings to all analytics scripts and made some basic syntax fixes
> Analytics functions and admin scripts

- frontend/public/index.html
- frontend/src/components/TaskCreator/Picker.module.css
- frontend/src/components/TaskView/FutureView/FutureViewControl.module.scss
- frontend/src/components/TaskView/FutureView/FutureViewControl.tsx
- frontend/src/components/TaskView/FutureView/FutureViewTask.module.css
- frontend/src/components/TaskView/index.tsx
- frontend/src/components/UI/SquareButtons.module.scss
- frontend/src/components/UI/SquareIconToggle.tsx
- frontend/src/components/UI/SquareTextButton.tsx
- frontend/src/components/Util/TaskEditors/FloatingTaskEditor.module.css
- frontend/src/components/Util/TaskEditors/FloatingTaskEditor.tsx
- frontend/src/components/Util/TaskEditors/TaskEditor/index.module.css
- frontend/src/hooks/window-size-hook.ts
Fixed #233 and #238.
It should also the fix the problem when it automatically scales on mobile
> Various Easy UI Fix

- frontend/src/components/TaskView/FutureView/FutureViewControl.module.scss
- frontend/src/components/TaskView/FutureView/FutureViewControl.tsx
- frontend/src/components/TitleBar/Onboarding/Onboard.module.scss
- frontend/src/components/TitleBar/Onboarding/Onboard.tsx
- frontend/src/components/UI/SamwiseIcon.tsx
> A11y improvements (Close #201, #230)

- frontend/src/components/Util/TaskEditors/TaskEditor/task-diff-reducer.ts
- frontend/src/store/store-types.ts
This pull request only add the not-connected-yet reducer and the Diff to enable @meganyin13 to work on the firebase actions.
> Add task-diff-reducer

- frontend/src/firebase/actions.ts
> Firebase actions (add editTaskWithDiff)

- frontend/.eslintrc
- frontend/package.json
- frontend/src/App.tsx
- frontend/src/components/TaskView/FutureView/FutureViewSubTask.tsx
- frontend/src/components/TaskView/FutureView/FutureViewTask.tsx
- frontend/src/components/Util/Modals/ChoiceModal.tsx
- frontend/src/components/Util/Modals/index.ts
- frontend/src/components/Util/Modals/index.tsx
- frontend/src/components/Util/TaskEditors/FloatingTaskEditor.tsx
- frontend/src/components/Util/TaskEditors/InlineTaskEditor.tsx
- frontend/src/components/Util/TaskEditors/TaskEditor/MainTaskEditor.tsx
- frontend/src/components/Util/TaskEditors/TaskEditor/OneSubTaskEditor.tsx
- frontend/src/components/Util/TaskEditors/TaskEditor/index.module.css
- frontend/src/components/Util/TaskEditors/TaskEditor/index.tsx
- frontend/src/components/Util/TaskEditors/TaskEditor/task-diff-reducer.ts
- frontend/src/components/Util/TaskEditors/editors-types.ts
- frontend/src/firebase/actions.ts
- frontend/src/firebase/firestore-types.ts
- frontend/src/index.tsx
- frontend/src/store/store-types.ts
- frontend/src/util/task-util.test.ts
- frontend/src/util/task-util.ts
- frontend/tsconfig.json
- frontend/yarn.lock
> TaskEditor v2 with partial support for repeated task

- frontend/src/components/TaskCreator/index.tsx
- frontend/src/firebase/firestore-types.ts
- frontend/src/firebase/listeners.ts
- frontend/src/util/undo-util.ts
> Fix type errors related to repeated task refactoring

- frontend/.eslintrc
- frontend/src/components/TaskCreator/index.tsx
- frontend/src/components/Util/Modals/index.tsx
- frontend/src/hooks/window-size-hook.ts
> Fix linter problem for hooks rules and fix modal init

- frontend/src/components/TaskCreator/DatePicker.module.css
- frontend/src/components/TaskCreator/DatePicker.tsx
- frontend/src/components/TaskCreator/Picker.module.css
- frontend/src/components/TaskCreator/index.tsx
- frontend/src/firebase/firestore-types.ts
- frontend/src/firebase/listeners.ts
- frontend/src/store/reducers.ts
- frontend/src/store/store-types.ts
- frontend/src/util/bitwise-util.ts
- frontend/src/util/const-util.ts
The task adder does not store repeating tasks yet. It just has the GUI support for it.
> Basic Repeating Task GUI

- frontend/src/util/ga-util.ts
> Fix is-staging config for google analytics

- frontend/src/components/TaskCreator/DatePicker.tsx
- frontend/src/components/TaskView/FutureView/FutureViewDayTaskContainer.tsx
- frontend/src/components/TaskView/FutureView/FutureViewNDays.tsx
- frontend/src/components/TaskView/FutureView/FutureViewSevenColumns.tsx
- frontend/src/components/TaskView/FutureView/FutureViewTask.tsx
- frontend/src/components/TaskView/FutureView/index.tsx
- frontend/src/components/Util/Modals/ChoiceModal.module.css
- frontend/src/components/Util/Modals/ChoiceModal.tsx
- frontend/src/components/Util/TaskEditors/FloatingTaskEditor.module.css
- frontend/src/components/Util/TaskEditors/FloatingTaskEditor.tsx
- frontend/src/components/Util/TaskEditors/InlineTaskEditor.tsx
- frontend/src/components/Util/TaskEditors/TaskEditor/index.module.css
- frontend/src/components/Util/TaskEditors/TaskEditor/index.tsx
- frontend/src/components/Util/TaskEditors/TaskEditor/task-diff-reducer.ts
- frontend/src/firebase/actions.ts
- frontend/src/util/datetime-util.ts
- frontend/src/util/task-util.ts
> Repeated task editing fix

- frontend/src/components/TaskCreator/index.tsx
- frontend/src/components/TaskView/FutureView/FutureViewSubTask.tsx
- frontend/src/components/TaskView/FutureView/FutureViewTask.tsx
- frontend/src/components/Util/Modals/index.tsx
- frontend/src/components/Util/TaskEditors/FloatingTaskEditor.tsx
- frontend/src/components/Util/TaskEditors/InlineTaskEditor.tsx
- frontend/src/components/Util/TaskEditors/TaskEditor/index.tsx
- frontend/src/firebase/actions.ts
- frontend/src/util/datetime-util.ts
- frontend/src/util/task-util.ts
> Repeated task forking bug fix and performance improvements

- frontend/src/components/TaskCreator/DatePicker.tsx
- frontend/src/components/TaskCreator/index.tsx
- frontend/src/util/bitwise-util.test.ts
- frontend/src/util/bitwise-util.ts
Finished the basic task creator for creating repeating tasks. Includes fixes for the Date Picker component, so that it computes end dates correctly. Does not have a way of storing how the user wanted the repeat to end yet (so it defaults to end date, rather than storing the number of occurrences, for example). Also right now it's number of weeks to repeat, not number of occurrences (to simplify math).
- Fixed a bug with the bitset utils that were off by one with day indexing. However, this fix seems to have caused problems in the future view, which was evidently expected the broken version of the bitset utils.
> Finished Task Creator for Repeating Tasks

- .github/PULL_REQUEST_TEMPLATE.md
> Removed documentation lines in pull request template

- frontend/src/firebase/actions.ts
> Fix complete focus bug

- frontend/src/components/Util/TaskEditors/TaskEditor/index.tsx
> Fix the bug that floating editor is not automatically closed on save

- frontend/src/components/TaskView/FocusView/FocusTask.tsx
- frontend/src/components/TaskView/FocusView/index.tsx
- frontend/src/components/TaskView/FutureView/FutureViewControl.tsx
- frontend/src/components/TaskView/FutureView/FutureViewDay.tsx
- frontend/src/components/UI/SamwiseIcon.tsx
- frontend/src/components/UI/UndoToast.tsx
- frontend/src/components/Util/Modals/index.tsx
- frontend/src/components/Util/TagListPicker/TagPickerItem.tsx
- frontend/src/store/selectors.ts
I go through the warnings and fixed and suppressed most of the them. The only remaining two are due to missing ts type definition, which should potentially be patched upstream rather than adding it here.
> [lint] Fix or suppress ESLint warnings

- frontend/src/util/task-util.ts
Changed some working according to @mt-xing 's suggestion
master template -> all occurences
fork -> this instance
> Use more human-readable words for master template and fork

- frontend/src/firebase/actions.ts
This is identical problem to #281
> Unbreak subtask deletion in future view

- frontend/package.json
- frontend/src/components/TitleBar/Settings/SettingsButton.test.tsx
- frontend/src/components/TitleBar/Settings/SettingsPage.test.tsx
- frontend/src/components/TitleBar/Settings/SettingsPage.tsx
- frontend/src/components/TitleBar/Settings/__snapshots__/SettingsButton.test.tsx.snap
- frontend/src/components/TitleBar/Settings/__snapshots__/SettingsPage.test.tsx.snap
- frontend/src/components/UI/CheckBox.test.tsx
- frontend/src/components/UI/Loading.test.tsx
- frontend/src/components/UI/OverdueAlert.test.tsx
- frontend/src/components/UI/SamwiseIcon.test.tsx
- frontend/src/components/UI/__snapshots__/CheckBox.test.tsx.snap
- frontend/src/components/UI/__snapshots__/Loading.test.tsx.snap
- frontend/src/components/UI/__snapshots__/OverdueAlert.test.tsx.snap
- frontend/src/components/UI/__snapshots__/SamwiseIcon.test.tsx.snap
- frontend/yarn.lock
Summary:
This commit aims to setup the basic snapshot tests. It's designed to be a template rather than a complete setup.
Test Plan:
See CI
> [tests] Add some easy snapshot tests

- frontend/src/components/Util/AppInit/LoginBarrier.tsx
- frontend/src/firebase/actions.ts
- frontend/src/firebase/auth-util.ts
- frontend/src/index.tsx
- frontend/src/util/ga-util.ts
Summary:
To collect absolute accurate data, this kind of tracking indeed needs to be done on the server side. However, if someone really wants to mess up the data, he can simulate these behavior anyways. Therefore, I think it's better and easier to just use Google analytics and let google do the aggregation math for us!
Test Plan:
- manually compare helper functions in frontend/src/ga-util.ts and `UserActionStat` in functions/src/types.ts to ensure that we track all the previous tracked data. The only missing thing is complete in-focus task, but I don't see that in our success metrics anymore.
- In the PR staging site, do some stuff and observe the Network tab in chrome debugger tool.
The collected data is not visible in Google Analytics yet, I guess it takes time. Therefore, I have not …
> Use Google Analytics to track events current tracked in functions

- frontend/src/components/TitleBar/Settings/SettingsButton.tsx
- frontend/src/components/TitleBar/Settings/__snapshots__/SettingsButton.test.tsx.snap
Makes the settings button a bit bigger.
Definitely not a hack.
- At some point we may want to make some DOM edits to make the actual thing the right size, rather than just `transform:scale`-ing the thing.
> Bigger Settings Button

- .github/workflows/ci-workflow.yml
Add a trailing `/` to the end of URL to help GitHub pages understand that we want `staging-pr.samwise.today/PR-NUMBER/index.html`.
> [pr-deploy] Tweak deployment bot comment

- README.md
Added "Pinxuan Huang" to README.md under "Since 2019"
> Add Pi to readme

- frontend/src/components/TitleBar/Settings/SettingsPage.test.tsx
- frontend/src/components/TitleBar/Settings/__snapshots__/SettingsPage.test.tsx.snap
- frontend/src/components/TitleBar/Tags/ClassTagAdder.test.tsx
- frontend/src/components/TitleBar/Tags/ColorEditor.test.tsx
- frontend/src/components/TitleBar/Tags/OtherTagAdder.test.tsx
- frontend/src/components/TitleBar/Tags/TagItem.test.tsx
- frontend/src/components/TitleBar/Tags/__snapshots__/ClassTagAdder.test.tsx.snap
- frontend/src/components/TitleBar/Tags/__snapshots__/ColorEditor.test.tsx.snap
- frontend/src/components/TitleBar/Tags/__snapshots__/OtherTagAdder.test.tsx.snap
- frontend/src/components/TitleBar/Tags/__snapshots__/TagItem.test.tsx.snap
- frontend/src/index.tsx
- frontend/src/store/index.tsx
- frontend/src/store/reducers.ts
- frontend/src/store/state.ts
- frontend/src/store/store.ts
The added tests are all passing! :)
I'm originally planning to add more tests on the big `FutureView` component, but it will be very flaky since it will render different stuff depending on the current time. To keep the diff small, I'm planning to leave it to the future.
> Better and more snapshot tests

- README.md
I added my name and role to the readme
> added myself to readme

- README.md
Adding myself to the Samwise devs readme now that I just joined the team!
This is what the developers list since 2019 looks like after this PR:
> add Peter (me) to devs in README

- README.md
> Update some facts in README

- frontend/src/components/TaskView/FutureView/FutureViewControl.tsx
Fix for #317. Bring back arrows in 5D future view.
This pull request is the first step towards implementing feature Foo
Enter Future View 5D view. Ensure left and right arrows appear on the sides.
Exact placement may be off.
> Bring back future view arrows

- frontend/src/components/Popup/AllComplete/index.tsx
This pull request fixes the confetti after you finish all the tasks in focus view!
https://www.youtube.com/watch?v=tyPrqmYK1Tg
(please watch with sound for the ideal experience)
> Fix confetti for focus task completion

- common/src/util/const-util.ts
Update the end dates for repeating tasks for the Spring 2020 semester.
Fix #399
> Update Dates for Spring 2020

- frontend/src/components/TaskView/FutureView/FutureViewDay.tsx
- frontend/src/components/TaskView/FutureView/FutureViewDayContent.tsx
Oops.
Idk how I missed that, but dates are visible in light mode again. Lmao.
Fix #406
> Fix Invisible Dates

- LICENSE
We finally get CLA stuff sorted for all contributors of the repo. We can finally relicense to AGPL 3.0 to be consistent with the rest of DTI's repo.
👀
> Relicense under AGPL 3.0

- common/src/util/const-util.ts
Update the end of semester dates to reflect the new calendar schedule.
> Update End of Semester Dates

- .github/workflows/cd-workflow.yml
Add staging Firebase credentials as a secret and have the CD pipeline write it to the appropriate file.
Let's see if it breaks.
> Modify CD Pipeline to have Staging Credentials

- .github/workflows/cd-workflow.yml
- deploy-functions
- package.json
- yarn.lock
- Make the script fail if any step fails
- Move the secret sdk generation code to the correct step
- Bump firebase-tools and hope it can fix our problems
Test in staging
> Misc improvements to deploy functions script

- deploy-functions.js
Apparently the CI doesn't allow the built-in fs remove directory command to delete recursively, so I got a function that does that manually.
Still runs on Windows.
> Fix Functions Deploy Script

- frontend/src/components/Util/TaskEditors/TaskEditor/index.tsx
> Delete Canvas tasks from Focus View too

- README.md
Added react-modal, react-dom-confetti, react-beautiful-dnd to dependencies list. Also changed the last updated date.
👀
> Update Frontend Dependencies List in README

- .eslintrc
- frontend/src/components/GroupView/RightView/GroupTaskRow/GroupTask.tsx
- frontend/src/components/TaskCreator/index.tsx
- frontend/src/components/TitleBar/GroupInvites/index.tsx
- frontend/src/components/UI/CheckBox.tsx
- frontend/src/components/UI/OverdueAlert.tsx
- frontend/src/components/UI/SamwiseIcon.tsx
- frontend/src/components/Util/TaskEditors/TaskEditor/RepeatFrequencyHeader.tsx
- package.json
- yarn.lock
Decided to suppress react/require-default-props since it doesn't understand the React pattern for TS.
CI
> Bump eslint-plugin-react

- common/package.json
- frontend/package.json
- functions/package.json
- package.json
- yarn.lock
This is a followup of #511. I originally tried to bump firebase in that PR but end up having too many type errors. I tried again this time. It turned out that the reason why I got so many errors last time is because I don't bump all the firebase deps together.
CI passes. Preview still loads.
> Bump firebase

- frontend/src/App.module.scss
- frontend/src/ViewSwitcher.tsx
> Unbreak empty group view's layout

- .github/workflows/ci-frontend.yml
I might be sleepy when I did this.
CI
> Remove duplicate setting of env var in ci-frontend.yml

- .github/workflows/tssa-analysis.yml
- package.json
- yarn.lock
The new tssa can support function-level dependency analysis, so it can produce a more precise list of symbols a change can affect.
It also contains @meganyin13's change to break down css change affect list by file.
Test when merged into master.
> Adopt tssa 0.0.9

- frontend/src/components/Util/TaskEditors/TaskEditor/index.tsx
Deleted save button from group task
> Deleted Save button from group task

- common/types/firestore-types.ts
- frontend/src/firebase/actions.ts
- frontend/src/firebase/listeners.ts
Correct the type of FirestoreGroup from Date to firestore.Timestamp.
Play test on staging but should not break anything
> update firestore group type and update listeners

- frontend/src/components/UI/OverdueAlert.module.scss
The release to get @ptwu's temporary fix for misplaced `!` badge into prod.
👀
> Patch release on October 17

- deploy-functions.js
Prevent the deploy job from SILENTLY failing again!
Tested locally and it can still run/
> Perform exit code check for functions deployment script

- frontend/src/components/Util/TaskEditors/FloatingTaskEditor.tsx
This pull request fixes task completion in future view's FloatingTaskEditor. Previously, we could check the checkbox to complete the task once, but it would only update once per hover+click, and was not very responsive. This is because during #635, we added the `active` prop to the `TaskEditor` when using the FloatingTaskEditor under the assumption that we needed to in order to prevent race conditions in updating the state of the task in the reducer. However, this turned out to not be the root cause of the deleting / corrupted data problem, as the real issue was that we were not editing tasks in a principled way through the reducer. Therefore, this `active` prop can be removed, and solves the issue in one line. 😎
> Fix FloatingTaskEditor checkbox and focus

- frontend/src/components/GroupView/MiddleBar/GroupViewMiddleBarTaskQueue.tsx
- frontend/src/components/GroupView/RightView/GroupTask.tsx
- frontend/src/components/GroupView/RightView/GroupTaskRow.tsx
- frontend/src/components/GroupView/RightView/GroupTasksContainer.tsx
- frontend/src/components/GroupView/RightView/index.tsx
- frontend/src/components/Util/TaskEditors/InlineTaskEditor.tsx
- frontend/src/components/Util/TaskEditors/TaskEditor/MainTaskEditor.tsx
- frontend/src/components/Util/TaskEditors/TaskEditor/index.tsx
- functions/src/send-email.ts
Clicking the bell icon now sends an email to the owner of the task as follows:
`${senderName} from ${group.name} is sending you a reminder to do ${task.name}!`
Playtest. Playtested w/ myself and one other.
> sending email notif about task

- frontend/src/firebase/index.ts
Without this line, it will die with `xxx.functions is not a function` when clicking on hug and bell icon.
Click on those icons.
> Unbreak send emails function for hug and bell icon

- README.md
Recognize @IshikaJain's contribution.
👀
> Add Ishika to README

- frontend/src/components/TaskCreator/index.tsx
I'm about to setup some hooks to allow better communications between task creator and its sibling components. This PR refactors TaskCreator to functional component to prepare for that change.
The conversion itself is straight forward. Most of the time it's just changing syntax, so it should be easy to review.
Test it in personal view and group view. Should both work.
> Convert task creator to functional component

- frontend/src/components/TaskView/FutureView/__snapshots__/FutureViewSubTask.test.tsx.snap
- frontend/src/components/UI/CheckBox.module.scss
- frontend/src/components/UI/CheckBox.tsx
- frontend/src/components/UI/__snapshots__/CheckBox.test.tsx.snap
- frontend/src/components/Util/TaskEditors/TaskEditor/MainTaskEditor.tsx
- frontend/src/components/Util/TaskEditors/TaskEditor/OneSubTaskEditor.tsx
- frontend/src/components/Util/TaskEditors/TaskEditor/index.tsx
This PR implements group task completion behavior for group tasks, by disallowing task & subtask completion and undoing completion if you are not the assignee of the subtask. It computes whether this is possible in the `TaskEditor` component and compares the owner of the group task with the current app user email, and passes this down to the `MainTaskEditor` and `OneSubTaskEditor` respectively.
Create a group and have some friends to be in the group with you. Make tasks for them and some subtasks. Try checking their subtasks (it shouldn't work). See that you can still check your own subtasks.
> Disallow group task completion if not the assignee

- frontend/src/components/Util/TaskEditors/TaskEditor/EditorHeader.tsx
- frontend/src/components/Util/TaskEditors/TaskEditor/index.tsx
Pass the type down for a more reliable check.
Bug fixed:
- group task no longer grabbable
- group task tag no longer editable
👀
> Ban all group task tag edit

- frontend/src/components/GroupView/MiddleBar/GroupViewMiddleBarTaskQueue.tsx
Fixes task queue checking and unchecking in group view, as pointed out by Matt. This was caused by my PR last night #688.
Not disabled anymore!
> Allow group task queue changes on tasks and subtasks

- frontend/src/components/GroupView/MiddleBar/GroupViewMiddleBarMemberRow.module.scss
- frontend/src/components/GroupView/MiddleBar/GroupViewMiddleBarMemberRow.tsx
- frontend/src/components/TaskCreator/index.module.scss
Fix button alignment in TaskCreator and align icons in MemberRow of GroupView.
> Fix button alignment

- frontend/src/components/GroupView/RightView/CompletedTasks/CompletedTask.tsx
> Color completed task in group view

- frontend/src/components/TaskView/FutureView/FutureViewTask.tsx
> Ensure future view group task also has correct color

- frontend/src/components/TaskCreator/index.module.scss
> Fix hidden submit task button on safari

- frontend/src/components/SideBar/AddGroupTags.module.scss
- frontend/src/components/SideBar/AddGroupTags.tsx
- frontend/src/components/SideBar/GroupIcon.module.scss
- frontend/src/components/SideBar/GroupIcon.tsx
- frontend/src/components/SideBar/index.module.scss
- frontend/src/components/SideBar/index.tsx
- frontend/src/components/TaskCreator/DatePicker.tsx
- frontend/src/components/TaskCreator/Picker.module.scss
- frontend/src/components/TitleBar/Settings/SettingsButton.tsx
- frontend/src/components/TitleBar/Settings/__snapshots__/SettingsButton.test.tsx.snap
- package.json
Fixed some bugs related to settings page launched from side bar.
Test the sidebar and the settings page launched from side bar.
> Bug Fixes Release after Group Task Launch

- common/firebase/common-actions.ts
- common/firebase/database.ts
- common/firebase/order-manager.ts
- common/types/firestore-types.ts
- frontend/src/firebase/actions.ts
Mostly finish #553, with only tasks collection left since that requires more refactorings.
Everything passes the type checker. Try to load the app to ensure that all the data validations have passed.
> Setup FirestoreDataConverter for most collections

- common/firebase/common-actions.ts
- common/firebase/database.ts
- frontend/src/components/GroupView/index.tsx
- frontend/src/firebase/actions.ts
Finally make all of our firestore operations strongly typed!
Try to load the app. All the runtime type validation passes.
> Setup firestore data converter for FirestoreTask. Close #553.

- common/util/const-util.ts
- frontend/src/components/Util/GroupMemberListPicker/SearchGroupMember.module.scss
> Fix member assign to box hidden behind subtasks

- common/firebase/common-actions.ts
- common/types/firestore-types.ts
- frontend/src/firebase/actions.ts
- frontend/src/firebase/listeners.ts
Move the code there so that it can be used by both frontend and functions code. Most of the change is just moving around code.
Check group editing operations and invitation still works.
> Refactor group related firestore actions into common package

- common/firebase/common-actions.ts
- common/store/actions.ts
- common/store/reducers.test.ts
- common/store/reducers.ts
- common/store/state.ts
- frontend/src/components/TaskView/FutureView/index.tsx
- frontend/src/components/TitleBar/Onboarding/Onboard.test.tsx
- frontend/src/firebase/actions.ts
- frontend/src/firebase/listeners.ts
- frontend/src/store/store.ts
Move the code there so that it can be used by both frontend and functions code. Most of the change is just moving around code.
Close #534.
Check the following features
- Clear focus
- Complete task in focus
- Reorder tasks in focus
- Complete onboarding
- Set canvas calendar
- Import course exam
> Refactor all firestore actions into common actions

- frontend/src/components/GroupView/RightView/index.module.scss
- frontend/src/components/GroupView/RightView/index.tsx
No design yet :(, so i just come up with my own.
Preview
> Support editing group deadline

- .github/workflows/e2e-course-info.yml
- package.json
Title
`yarn workspace course-info fetch` seems to work
> Make course-info a workspace

- .github/workflows/e2e-course-info.yml
- course-info/package.json
- course-info/src/create-json.ts
- course-info/src/fetch-courses.ts
- course-info/src/fetch-exam.ts
- course-info/src/main.ts
- course-info/src/merge-json.ts
- course-info/tsconfig.json
- yarn.lock
This PR unbreaks the script that's failing for a while, and added support for final exams when they are ready.
I also improved the bot so that it can output diff in the PR body as well.
CI
> Unbreak course json script and improve bot
