admin/frontend/src/ControlPanel/index.tsx
This pull request simply changed default limit from 7 to 1 so that less data are fetched by default. It can help reduce the db usage when we are reading analytics data.
=> Reduce the default limit to reduce unexpected usage

firestore.rules, frontend/src/components/TitleBar/Banner/index.css, frontend/src/components/TitleBar/Banner/index.tsx, frontend/src/components/TitleBar/Banner/messages.ts, frontend/src/components/TitleBar/TitleBar.css, frontend/src/components/TitleBar/TitleBar.tsx, frontend/src/firebase/actions.ts, frontend/src/firebase/db.ts, frontend/src/firebase/listeners.ts, frontend/src/store/action-types.ts, frontend/src/store/actions.ts, frontend/src/store/reducers.ts, frontend/src/store/selectors.ts, frontend/src/store/store-types.ts
I added another collection in firestore called `samwise-banner-message`. Each document in the collection has this format: `{ [messageId]: true | false | undefined }`, whether `true` means that the user dismissed the message and `false | undefined` means that the user has not dismissed it.
The frontend has a set of potential messages to display. Currently, it will display the latest message that is not dismissed, but it can be easily changed in the future.
This pull request also adds our first banner message to apologize for the outage last night.
=> Setup system for banner message and added first apology banner

frontend/src/components/TaskView/FutureView/FutureViewDay.tsx, frontend/src/components/TaskView/FutureView/FutureViewTask.css, frontend/src/components/TaskView/FutureView/FutureViewTask.tsx, frontend/src/components/TaskView/FutureView/future-view-css-props.ts, frontend/src/components/UI/OverdueAlert.css, frontend/src/components/UI/OverdueAlert.tsx, frontend/src/components/Util/TaskEditors/TaskEditor/index.tsx
Before:
After:
Note: The deformed checkbox problem is not related to this one. It should be fixed independently in #175.
=> Fix overdue alert position in future view

frontend/src/util/task-util.test.ts, frontend/src/util/task-util.ts
Now an uncompleted focus task with no subtask will not show up in completed section.
Additional blackbox tests have been added in `src/util/tasks-util.test.ts` to ensure there will be no regression.
=> Fix the task filtering bug

.circleci/config.yml
Instead of using the branch filtering in the bash command, it does the filtering at the workflow job level. This can prevent downloading the docker container when at the end it's just immediately discarded
=> Speed up circle ci build

frontend/src/components/TaskView/FutureView/index.tsx, frontend/src/components/TaskView/TaskView.css
Adjusted width of the focus view to make it stick to the design.
Also changed the breakpoints of n-days view to make the cards not too narrow.
=> Fix focus-to-future view ratio. (Fix #138)

frontend/src/components/Popup/AllComplete/Celebrate.module.css, frontend/src/components/Popup/AllComplete/index.tsx, frontend/src/components/TitleBar/Onboarding/Onboard.module.css, frontend/src/components/TitleBar/Onboarding/Onboard.tsx, frontend/src/components/TitleBar/Settings/SettingsPage.tsx, frontend/src/firebase/actions.ts
- Confetti now triggers correctly even with subtasks, resolving #212 
- Onboarding page now has a checkbox to import exams, not a button.
- Settings page import button has been relabeled as a reimport button
- Restarting the tutorial from Settings now only plays the tutorial, not the onboarding screen (which looked confusingly similar to the settings page the user just came from)
=> UI Fixes: Confetti and Onboarding

firebase.json
create-react-app puts the build in build folder, not dist. It is now corrected.
=> Fix Circle CI deployment

.circleci/config.yml
We should always use LTS so that we don't run into problems in this [failed job](https://circleci.com/gh/cornell-dti/samwise/403) later. This pull request unbreaks master deploy.
Proof that this docker container exists: https://circleci.com/docs/2.0/docker-image-tags.json
Search for `lts-jessie-browsers`. Other than that, test in prod.
=> [ci] Ensure consistency of node version in two CI jobs

frontend/src/components/TaskCreator/index.tsx, frontend/src/components/TaskView/FutureView/FutureViewTask.tsx, frontend/src/components/Util/TaskEditors/FloatingTaskEditor.tsx, frontend/src/components/Util/TaskEditors/InlineTaskEditor.tsx, frontend/src/components/Util/TaskEditors/TaskEditor/EditorHeader.tsx, frontend/src/components/Util/TaskEditors/TaskEditor/index.tsx, frontend/src/components/Util/TaskEditors/editors-types.ts, frontend/src/firebase/actions.ts, frontend/src/firebase/firestore-types.ts, frontend/src/firebase/listeners.ts, frontend/src/store/reducers.ts, frontend/src/store/selectors.ts, frontend/src/store/store-types.ts, frontend/src/util/datetime-util.ts, frontend/src/util/task-util.ts, frontend/src/util/undo-util.ts
It is a design mistake to use a separate field to store repeat metadata.
Reasons:
- It doesn't make a lot of sense to also keep `date` field for RepeatingTask. Before this change, we only use that to store time info, which is hard to statically ensure that we correctly populate it.
- It gives us a false sense of security that we have correctly dealt with the complexity of repeating task. Since we kept `date` field, TypeScript won't complain in a lot of places where we forget to consider that `date` in RepeatingTask has special meanings.
Therefore, I decide to make `date` to have different types for OneTimeTask and RepeatingTask, so we can use TypeScript to tell us where we did it wrong.
The majority of this commit is simply changing `repeatingPattern` to `date`, but I do discover a bug …
=> Store `RepeatMetaData` into `date` field for task

frontend/src/util/task-util.ts, frontend/src/util/undo-util.ts
Background:
Hopefully we can deploy a new version with the new exam and date information soon. However, without this commit, if we disable the currently unstable repeating task feature, our current product will be worse than the deployed one since we lose the undo remove task feature and need to prompt the user to delete the task.
My temporary solution and deployment plan:
Restore undo feature for non-forked one-time tasks. After this commit lands, create another commit that only enables repeating task creation UI with a flag. Since we don't support switching between one-time tasks and repeating tasks yet, it will effectively disable repeating task feature, which can unblock our deployment.
Why is non-forked one-time task special?
It's the simplest kind of task we know how to deal with …
=> Restore undo task remove for non-forked one time task

frontend/src/components/TaskCreator/DatePicker.tsx
This commit continues the deployment preparation starting from #277
By default, it will not be enabled and won't be accidently enabled because you have to set local storage in console manually.
To check I don't remove the feature completely, run `localStorage.set('REPEATING_TASK_ENABLED', 'true')` and refresh, the feature will reappear. Unset it, it will disappear. It's expected that this flag will be removed once we deployed a stable version to production.
=> Put repeating task behind a flag

frontend/src/components/Util/TaskEditors/TaskEditor/index.tsx
#273 adds the missing line to the wrong place. After this fix, we will no longer close FloatingEditor after mouse moves out of the editor.
=> Fix the bug where we lose edit status on mouseleave

admin-scripts/add-type-one-time.py
To deploy a new version to production, we first need to normalize the database to  use the latest schema with the additional type field. This script does the normalization.
To ease your testing, changing 500 to 2 in the code.
1. Create 5-6 random tasks on the staging site.
2. In firebase console, remove the type field.
3. Download firebase admin sdk of the STAGING site and put it in admin-scripts/firebaseadmin.json
4. `python3 add-type-one-time.py`
5. Observe the firebase console. The field should be added back.
I have run this on my machine, but it's highly recommended that a code reviewer also run this to ensure we don't mess up the production db.
=> Add script to add `type: 'ONE_TIME'` to all existing task

frontend/src/firebase/actions.ts
Firebase does not like undefined values in update object. As a result, it will crash with the old code. This bug appears when you are checking a subtask in `FutureView`.
Test Plan:
See hot-fix deployed to samwise.today.
=> Avoid firebase crashing when date is undefined

.github/workflows/ci-workflows.yml
We want to see pr changes get deployed so that we can directly play with it without installing anything.
We want deployment to happen in isolation with other PR so that they don't interfere.
1. Build the frontend assets with the branch name as the root path. In this way, we can deploy stuff to a subdirectory with all the URL still correctly resolved.
2. Do some git magic to put the built stuff into the corresponding `gh-pages` branch, commit, and push.
3. Now it will be automatically deployed by GitHub Pages. Profit!
- Deploy to Firebase: Firebase does not allow us to programmatically create new sites within the same project.
- Deploy to Netlify/zuit: No good support for subdirectory only deploy. The problem is that we still want to keep other branches stuff around, so we must use git, …
=> [ci-cd] Setup GitHub actions to check, build, and deploy PR changes

.github/workflows/ci-workflow.yml, .github/workflows/cleanup-workflow.yml
=> Add cleanup workflow to remove staging resources after closing PR

frontend/src/components/TaskView/ProgressTracker/ProgressIndicator.module.scss, frontend/src/components/TaskView/ProgressTracker/ProgressIndicator.tsx
`height: '100%'` uses up the space for bear. Use `flex: auto` to automatically reserve space for bear
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ⬆️
=> Bring back the bear

.github/workflows/cd-workflow.yml
Add the missing `cd frontend` since everything is installed in `frontend` folder.
Test in `master`.
=> Unbreak master deploy by adding missing `cd frontend`

frontend/package.json, frontend/src/firebase/index.ts, frontend/src/util/ga-util.ts, frontend/yarn.lock
Firebase finally released analytics for web. Let's do everything in Firebase.
This makes ReactGA unused, so I removed it from package.json.
Analytics still works:
=> Use firebase analytics

.github/workflows/release-workflow.yml
Setup a release workflow. The config is mostly copied from cd workflow, but tweaked a little bit to use the production config: (`yarn build` instead of `yarn buiild:stage`, `use production` instead of `use default`).
I added another check `check-base-ref` in the workflow. It enforces that the base_ref is master, so we know everything goes through staging first.
To prevent abuse of release branch, an extremely strict branch protection rule has been setup. Merging to release requires three approvals, pushing after approval invalidates it, all status checks must pass, and branch must be up-to-date, etc. When all the conditions passed, only repo admins can push to release.
See the dummy first few commits to see whether we get the `check-base-ref` job right.
It should be merged by `squash and …
=> [cd] Create release workflow

frontend/src/App.module.css, frontend/src/App.tsx, frontend/src/components/TaskView/FutureView/FutureViewControl.tsx, frontend/src/components/TaskView/ProgressTracker/Bear.module.css, frontend/src/components/TaskView/ProgressTracker/ProgressIndicator.module.scss, frontend/src/components/TaskView/ProgressTracker/ProgressIndicator.tsx, frontend/src/components/TaskView/ProgressTracker/index.module.css, frontend/src/components/TaskView/index.module.css, frontend/src/components/TaskView/index.tsx, frontend/src/components/TitleBar/Settings/SettingsButton.module.css, frontend/src/index.scss
This pull request is the first step towards making mobile experience suck less.
- iPhone screenshot showing focusing in InputBox is no longer zoomed (although the UX is still terrible)
- The bear is finally back on iOS:
- Better 2W nav
<div>
</div>
=> Mobile improvements

frontend/src/components/TaskView/FocusView/index.module.css
Removed the ugly scrollbar in the focus view.
Scrollbar is gone when unneeded: 
But comes back when it is:
Also tested on mobile preview via dev console; looks fine.
=> Remove Focus Scrollbar

frontend/src/components/Util/TaskEditors/TaskEditor/MainTaskEditor.tsx, frontend/src/components/Util/TaskEditors/TaskEditor/OneSubTaskEditor.tsx, frontend/src/components/Util/TaskEditors/TaskEditor/index.tsx
Got rid of save prompt for checking and focusing a task in focus view. 
Also added this functionality for subtasks in focus view.
This pull request is the first step towards launching repeating task
Create a repeating task with subtasks. Make it focused. From focus view, mark the task as complete. Ensure that this task is also marked as completed in future view and that you are not prompted to save for this change. Do the same for marking subtasks of this repeated task as complete. Repeat with focusing/pinning this task from focus view.
=> No save focus and check

frontend/src/components/TitleBar/Tags/ColorEditor.module.css, frontend/src/components/TitleBar/Tags/TagItem.module.css
The code added in this PR changes the UI in screen widths below 500px, by removing the name of the color in order to condense the ColorPicker dropdown width. This fixes the overlapping text at small phone screen widths.
This pull request resolves issue #304.
=> Fix overlapping ColorPicker with class name on mobile settings page

.github/workflows/ci-workflow.yml, .github/workflows/release-workflow.yml
Move the enforcement of `master -> release` workflow to the pull request CI job.
See CI log for the enforcement workflow.
Unfortunately, the release job can still only be tested during release.
Relevant Docs:
https://help.github.com/en/articles/contexts-and-expression-syntax-for-github-actions
=> Fix deployment workflow

frontend/package.json, frontend/src/components/TitleBar/Settings/SettingsButton.tsx, frontend/src/components/TitleBar/Settings/__snapshots__/SettingsButton.test.tsx.snap, frontend/src/components/TitleBar/Settings/__snapshots__/SettingsPage.test.tsx.snap, frontend/src/components/TitleBar/Tags/__snapshots__/ColorEditor.test.tsx.snap, frontend/src/components/TitleBar/Tags/__snapshots__/OtherTagAdder.test.tsx.snap, frontend/src/components/TitleBar/Tags/__snapshots__/TagItem.test.tsx.snap, frontend/src/components/UI/SamwiseIcon.tsx, frontend/src/components/UI/SquareIconToggle.tsx, frontend/src/components/UI/__snapshots__/SamwiseIcon.test.tsx.snap, frontend/src/components/UI/samwise-icon-types.tsx, frontend/yarn.lock
This pull request adds more descriptive and user-friendly tooltip alt texts (as well as a new icon type to describe the Close Settings button as it is the same as the delete 'x' buttons).
=> Fix misleading/default tooltip values

frontend/src/components/Util/TaskEditors/TaskEditor/MainTaskEditor.tsx, frontend/src/components/Util/TaskEditors/TaskEditor/NewSubTaskEditor.tsx, frontend/src/components/Util/TaskEditors/TaskEditor/OneSubTaskEditor.tsx
This lastpass overlay is very annoying! Add new props to disable it according to https://stackoverflow.com/questions/50145270/hide-last-pass-icon-in-input-fields
Before:
After:
=> [editor][misc] Hide lastpass form fill overlay

.github/workflows/cleanup-workflow.yml
The cleanup workflow doesn't actually cleanup. Try to fix it according to: https://github.community/t5/GitHub-Actions/Running-a-job-on-pull-request-merge-in-specific-branch/m-p/34192#M1829
I will close the PR to see what happens.
After I closed the PR, this job is indeed triggered:
https://github.com/cornell-dti/samwise/commit/64cc4b50b014512871ff7266c28895296394e94e/checks?check_suite_id=258206304
Before close bot commit:
https://github.com/cornell-dti/samwise/commit/1e8282ca923de096f6e50ccb1a549c66c227f807
After close bot commit:
https://github.com/cornell-dti/samwise/commit/d99891f911a5338f27562a033e92db2d96066c9c
=> [ci] Fix cleanup workflow

firestore.rules
The changed line appears to have a mix of tabs and space before 🤔. Not sure what happened. Now unifying it to 2-space to be consistent with the rest of the codebase.
eyes
=> [misc] Fix weird indentation in firestore.rules

frontend/src/components/TaskCreator/DatePicker.tsx, frontend/src/components/TaskCreator/Picker.module.css
Added CSS class "RepeatSpecialEndDate" and child "RepeatSpecialEndDate button"
Added aforementioned styling to the <p> containing last day of class and last day of finals buttons
Fix the CSS itself however you want; maybe I added too much margin. I used 3px, but 2px is probably ok.
=> Last Day of Class button gets its style

frontend/package.json, frontend/src/components/TaskView/FutureView/FutureViewControl.tsx, frontend/src/components/TaskView/FutureView/FutureViewDayTaskContainer.tsx, frontend/src/components/TaskView/FutureView/__snapshots__/index.test.tsx.snap, frontend/src/components/TaskView/FutureView/index.test.tsx, frontend/src/components/TaskView/FutureView/index.tsx, frontend/src/components/TitleBar/index.tsx, frontend/src/hooks/time-hook.ts, frontend/yarn.lock
Last time I tried to add more snapshot tests to increase the test coverage of samwise. The journey stops at `FutureView` because it uses `new Date()` all over the place. Using `new Date()` prevents effective snapshot testing because a snapshot taken on date A will fail on date B.
Unifying the usage of current time is a necessary step to solve the issue. If we can shield all usage of current time behind a framework, then we can easily dig some hole in the framework for overriding the system time with our hardcoded time for deterministic testing, as shown in this diff.
Unifying the usage also has another advantage: when we plan to support more specific time like `2019-10-30 17:00` in the future, we don't have to look all over the codebase to hunt down the usage of `new Date()` because it …
=> Start to unify usage of current time for deterministic testing

frontend/src/components/TitleBar/Tags/ClassTagAdder.tsx, frontend/src/components/Util/SearchBox/index.tsx
Make the search box much faster by only searching when at least 3 characters have been typed.
This is the same behavior as exhibited on the Cornell Course Roster.
On my development machine, this change entirely eliminated all lag when searching courses, down from the nearly two second delay on the current staging site when typing in a class name.
This is particularly nice because the nature of React means that until the search completes, the search input DOM doesn't actually update, which means users don't see the characters they've typed for multiple seconds. That's fixed.
Also updated the class search box to use the name of the course with all whitespace and non-alphanumeric characters stripped as one of the keys. This helps with students searching class names but getting the spacing …
=> Search Box Optimization

.github/workflows/ci-workflow.yml
Using this well-maintained github action instead of writing git magic on our own:
https://github.com/peaceiris/actions-gh-pages
If you see the source of that github action, it does some more sophisticated magic than mine original git scripts, which is probably the reason why using this action fixed the problem.
If it works, `gh-pages` branch will show deployment status again.
It works: https://github.com/cornell-dti/samwise/commit/80716749153d3cc74ad26f87bbb96d99019baa45
See the green check. Previous commits do not have that.
=> Try to unbreak CI staging deploy

frontend/src/components/Util/TaskEditors/FloatingTaskEditor.module.css, frontend/src/components/Util/TaskEditors/FloatingTaskEditor.tsx
Added overflowY auto along with a maxHeight style to the editorPosDiv in future view which allows the user to scroll and see an unlimited number of subtasks, and be able to click the save button even with a large number of subtasks.
=> Fix off screen save button in FutureView editor

frontend/src/components/TaskCreator/DatePicker.tsx, frontend/src/hooks/time-hook.ts, frontend/src/util/datetime-util.test.ts, frontend/src/util/datetime-util.ts, frontend/src/util/task-util.ts
When creating a task to add to firebase/render, create the task start time as 00:00:00 and the end time 23:59:59. This solves the issues with respect to inclusivity and exclusivity on either end of the repeating task. 
Semantics can be improved/made more clear for "stops after x weeks".
Additionally fixes an issue that was not posted: creating repeating tasks does not exclude the first day after the repeat task duration when rendering the tasks.
=> Repeat task today

frontend/src/components/TaskCreator/DatePicker.tsx
Hopefully repeating task is stable enough. Let's ungate it so everyone can test it in staging. Once that's good, goes to prod.
Open chrome developer tools, clean all app data, should still see repeating task creation option
=> Ungate repeating task creation

frontend/src/App.tsx, frontend/src/components/UI/ModeIndicator.module.css, frontend/src/components/UI/ModeIndicator.test.tsx, frontend/src/components/UI/ModeIndicator.tsx, frontend/src/components/UI/__snapshots__/ModeIndicator.test.tsx.snap, frontend/src/util/mode-util.test.ts, frontend/src/util/mode-util.ts
This pull request implements the mode indicator for different environments.
I also take the opportunity to unify some of our environment detection code.
Dev: `yarn start`
Staging: `yarn build:stage && serve build/`
Prod: `yarn build && serve build/`
=> Implement mode-indicator

frontend/src/components/Util/TaskEditors/FloatingTaskEditor.tsx, frontend/src/components/Util/TaskEditors/InlineTaskEditor.tsx, frontend/src/components/Util/TaskEditors/TaskEditor/MainTaskEditor.tsx, frontend/src/components/Util/TaskEditors/TaskEditor/NewSubTaskEditor.tsx, frontend/src/components/Util/TaskEditors/TaskEditor/OneSubTaskEditor.tsx, frontend/src/components/Util/TaskEditors/TaskEditor/index.tsx
Brought back autosave via a 0.5 second refresh after user adds/edits a one time task. Repeated subtask has save button which prompts whether to fork the task or edit master template.
Additionally resolved CLA problem from *John Doe* in #338 🤔
This pull request unblocks repeated task.
Create a one time task and focus it. Type a new subtask for that task and press enter or tab. Ensure that that subtask shows up under that task in future view like so (try adding multiple subtasks to be *really* sure). Notice that there is no save button.:
Now try editing parts of the whole task (such as edit an existing subtask, change the date/class) ensure that these changes are propagated to the future view task.
Create a repeating task and add a new subtask. Click the save button. In the modal that …
=> Bring back autosave

frontend/.eslintrc
This is not intended to get rid of all of them. That's why I didn't set it to error.
However, I think we need a way to know how many TODOs there are in our codebase so that they will not be forgotten. Creating some warnings can make developers feel a little unconfortable so that they will eventually be resolved.
`yarn lint`. You will see
```
/path/to/samwise/frontend/src/components/TaskCreator/DatePicker.tsx
362:7  warning  Unexpected 'todo' comment  no-warning-comments
```
You can also see it in CI.
=> Warn against TODO/FIXME/XXX comments

frontend/src/hooks/window-size-hook.ts
Problem: right now resizing window is very expensive.
Whenever the size changes, the listener will be triggered. We have a bunch of places that call the hook; however, most of the places are only interested in whether the window size means a desktop or mobile view, in other words, a mapped value.
A mapped value changes less often than window size. Right now, we are unconditionally rerendering the view even if the mapped value does not change. This PR aims to change that.
This PR duplicates some code so that we will only call the `setMappedValue` function only if the mapped value actually change. In this way, we can avoid unnecessary rerenders.
Try to resize. Nothing breaks. Things should be much faster.
=> Improve performance for useMappedWindowSize hook.

frontend/src/components/Util/TaskEditors/TaskEditor/index.module.css
Fix problem in #369.
We should really avoid using negative margin hack in CSS. It usually causes more trouble than it solves.
=> Fix top padding of TaskEditor. Close #369

frontend/src/components/TaskCreator/DatePicker.tsx
Get rid of this warning. Since weekday string is not unique, we need to use index as well. I do not use the array index to avoid the eslint error.
Play with DatePicker. Nothing breaks. :eyes:
=> Fix React warning of no unique key in DatePicker

frontend/src/components/Util/TaskEditors/TaskEditor/index.tsx
Suppose you exit before the TaskEditor can save, then the edit is forever lost.
This diff ensures that things are always saved by calling `onSave` before `onMouseLeave` and `onBlur`, two events that indicates that TaskEditor might exit.
With this change, we can increase the interval of running `onSave` to a higher value: 1000ms.
Play with `TaskEditor`. Type something really fast and then let mouse leave the editor. Things should be saved.
=> Call `onSave` when `TaskEditor` lose focus

frontend/src/components/TitleBar/Canvas/CanvasCalendar.module.css, frontend/src/components/TitleBar/Canvas/CanvasCalendar.tsx, frontend/src/components/TitleBar/Settings/SettingsPage.tsx, frontend/src/components/TitleBar/Settings/__snapshots__/SettingsPage.test.tsx.snap, frontend/src/firebase/actions.ts, frontend/src/firebase/listeners.ts, frontend/src/store/state.ts, frontend/src/store/store-types.ts
Add a field at the bottom of Settings that allows users to add their Canvas calendar feed link. This calendar feed is able to be unlinked. A help link is included below the field in case users have trouble finding their Canvas calendar feed link.
Adds a _canvasCalendar_ field to documents in _samwise-settings_ in Firestore.
=> Add Canvas calendar field

frontend/src/components/Util/TaskEditors/TaskEditor/OneSubTaskEditor.tsx
This bug is introduced a while ago while we added autosave back in #309.
The fix is simple: save the edit to the local reducer first. The call of `editSubTask` will just fail silently and harmlessly.
Create a task, type one character in add subtask box and click checkbox very quickly. It's indeed saved.
=> Fix checking unsaved subtask. Close #354

frontend/src/components/Util/TaskEditors/TaskEditor/index.tsx
This is a regression introduced in #373.
We shouldn't unconditionally call onSave because it will trigger a modal during repeating task edit. The current master will popup the modal whenever you type any character. (In other words, current master's repeating task is broken.)
Observe the bug in current master. The bug is gone in this branch.
=> [editor] Guard implicit `onSave` call with `type === 'ONE_TIME'` check

functions/src/focus-today-task.ts, functions/src/index.ts
Automatically focus tasks due today with firebase functions.
I do not deal with potential timezone problem for the following reasons:
- We don't record user's timezone in the database.
- We assume users are in EST, and servers are in US. Having at most 3 hours off doesn't seem to be a big problem for this use case.
Create a task due today and unfocus it in any staging or local env.
Go to firebase functions tab, find the function `FocusTasksDueToday`, click view on cloud schedular, and force trigger a run over there.
You should see your task got focused.
Auto focusing repeating task involves more math. We have the calculation code in the `frontend` package. I want to deal with it after we found a good way to avoid duplicating code in two packages.
=> Auto-focus tasks due today

frontend/src/components/TaskCreator/DatePicker.tsx
Missing this warning since it's hidden in repeating task date picker.
Go to repeating task date picker in `TaskCreator`. No more warnings in console.
I simply suppressed the eslint warning since the array is stable.
=> Fix no-unique key React warning for end option radios in DatePicker

functions/src/iCalFunctions.ts
`parseICal` now updates existing tasks by updating the due date of the task and name of the task instead of doing nothing when the task already exists inside of a user's tasks.
Passes yarn tsc and no linter errors
Observe that a hypothetical assignment: "NOT DEV ASSIGNMENT" is due on the 13th.
However, the professor decides that such an assignment due on the 13th is very unlucky, so they move the due date to the 14th and rename the assignment. After the next round of fetching ical information, such a change would be reflected as such:
Of course, this can be replicated by manually calling parseICal link after there is a desync between the canvas event on the iCal and the canvas event stored in firestore. 
I update name and date of the task only. More fields can be included/excluded, but if …
=> iCal resync

frontend/src/components/TaskView/index.tsx
Fixes #389. At 840px half of screen is focus view and half is one day of Future View
This pull request is the first step towards implementing feature Foo
Set screen width to 840px. Ensure that half of screen is focus and half is future view:
=> Fix 840 Screen Width

course-info/fetch-exam.js, course-info/merge-json.js, course-info/run
This diff simply unbreaks it. Now it can generate a JSON we want. I forgot what's the process of putting the JSON to the right place and ensure there is no compatibility problems. Let's leave that to today's work session.
In the long term, we should think about how we can make this more maintainable. I'm happy to rewrite the script in TS and move my `cornell-api-libs` to DTI org.
```bash
cd course-info
./run
```
=> Unbreak course scraper for SP20

course-info/run
Now I moved the repo to DTI org, let's make our script clone the DTI repo.
I also make it call the gradle wrapper so that people don't have to install gradle.
I updated dependency to reflect the fact that JDK11 is required.
```bash
cd course-info
./run # things still run
```
=> Make course scraper use `cornell-api-libs` in DTI org

common/src/types/store-types.ts, common/src/util/task-util.test.ts, frontend/src/components/TaskCreator/index.tsx, frontend/src/components/TaskView/FutureView/FutureViewTask.tsx, frontend/src/components/Util/TaskEditors/FloatingTaskEditor.tsx, frontend/src/components/Util/TaskEditors/InlineTaskEditor.tsx, frontend/src/components/Util/TaskEditors/TaskEditor/EditorHeader.tsx, frontend/src/components/Util/TaskEditors/TaskEditor/MainTaskEditor.tsx, frontend/src/components/Util/TaskEditors/TaskEditor/index.tsx
Disabled editing of task name, due date, and delete option for tasks imported from canvas feed.
Before:
After:
=> Disable canvas editing

.github/workflows/e2e-course-info.yml
This pull request tries to let @dti-github-bot automatically create a PR when the E2E test on course info json failed. I hope this can reduce our burden to update stuff.
Ideally, we can show the diff inline in the created PR comment, but it might us to switch the entire workflow to github actions. It's not too bad to look at the latest master E2E test failure to see what's changed, so I decide not to implement it, as least in this diff.
See CI running result. The PR is created in https://github.com/cornell-dti/samwise/pull/412.
The consistency test is designed to fail, so that the PR creation job can be triggered. The create PR job also fails because the PR is already created. This error cannot be try-catched, but I don't think it's too big because it can remind people to review PRs. :)
=> Automatically create PR to update JSON when E2E course-info failed

frontend/src/components/Util/TaskEditors/InlineTaskEditor.tsx, frontend/src/components/Util/TaskEditors/TaskEditor/index.tsx, frontend/src/components/Util/TaskEditors/TaskEditor/task-diff-reducer.ts
This is a partial attempt to make the TaskEditor more manageable, with some of the spirit in #351.
It still does not completely solve the problem of focus state getting lost while the DOM get nuked, but we can observe that the same problem also exists in the `FloatingTaskEditor` in the future view. Historically, `FloatingTaskEditor` breaks much less often than `InlineTaskEditor`, so I think the current approach is not complete nonsense. If we think about it carefully, we will find that the major difference between `FloatingTaskEditor` and `InlineEditor` is that `FloatingTaskEditor` is guaranteed to be active when the component got rendered, while the same is not true for `InlineTaskEditor`. This creates a problem where `FloatingTaskEditor` does not need to care about state getting …
=> Use `active` prop to decide whether to override state with props in `TaskEditor`

.github/workflows/e2e-course-info.yml
Even if it's checking twice a day, we don't review code that often and sometimes we will batch json updates. Let's reduce the frequency to be only run on Mon/Wed/Fri to reduce the noise. I choose workdays because part json update record shows that cornell does not update these information on weekends.
Screenshot taken from github actions online editor, which shows that it does what's suppose to do.
=> Reduce course json update frequency

frontend/src/components/TaskCreator/DatePicker.tsx, frontend/src/components/TaskCreator/FocusPicker.tsx, frontend/src/components/TaskCreator/TagPicker.tsx, frontend/src/components/TaskCreator/__snapshots__/FocusPicker.test.tsx.snap, frontend/src/components/TaskCreator/__snapshots__/TagPicker.test.tsx.snap
Adds a `onKeyPress` event handler to each of the picker components (TagPicker, FocusPicker, and DatePicker).
- Open the create a new task editor
- Tab to one of the pickers (focus picker, tag picker, or date picker)
- Pressing the enter key or spacebar should activate the picker
=> Fix tab editor issue

functions/canvasFunctions/canvasFunctions.ts, functions/json-bigint.d.ts, functions/src/iCalFunctions.ts, functions/src/ical-parser.ts, functions/src/index.ts
Fix linter warnings and strictify some types instead of `any`.
Deployed it to staging and run it without any problems. However, I did notice a preexsting problem. The implementation removes all whitespaces in a line, which causes the task names to be very ugly. See issue #450.
=> Fix all linter warnings

.github/workflows/ci-frontend.yml
The previous setup will add a new comment whenever the PR has updated commits. That's quite annoying.
I wrote a new github actions in https://github.com/cornell-dti/dti-repo-tools to avoid this by editing the already posted commit. (In case the content is the same, it will be a no-op). This diff switches to use that github action.
Added a second commit to test its effect. You will find that no more commits are posted by the bot.
=> Cleaner bot comment

frontend/src/components/TaskView/FutureView/FutureViewDay.tsx, frontend/src/components/TaskView/FutureView/FutureViewDayContent.tsx, frontend/src/components/TaskView/FutureView/FutureViewDayTaskContainer.tsx
This pull request fixes a bug present in production and development where if a user has many subtasks/tasks in a single day such that it overflows the viewport bottom, the `More Tasks...` button no longer appears to allow the user to enter `FloatingView`.
This bug was likely introduced by #376, as the `taskListComponent` in the `FutureViewDayTaskContainer` began to house `Draggable` tasks in its container, which do not conform to normal `scrollHeight` and `clientHeight` values. What ended up happening was that these values were both equal, and as a result the `onHeightChange` function call always passes `false` for `doesOverflow`, and now `FloatingView` cannot be accessed. This pull request solves that by ~~replacing the `containerHeight` with a calculated height based on the viewport and …
=> Make More Tasks button appear again + fix FloatingView position

common/src/types/firestore-types.ts, frontend/src/firebase/listeners.ts
During the refactoring of #427, we moved all non-common fields of tasks into the metadata object. The transformation is done in `src/firebase/listeners.ts`. The transformer forgets to put the `icalUID` field into `metadata` object, which makes a lot of canvas task check break.
The reason we didn't catch the bug or didn't notice it is that the field is not even declared in its firebase types! Now we declare the field and fix the transformer.
Canvas tasks cannot be deleted anymore. See the screenshot.
=> Disallow editing/deleting canvas task again

frontend/src/components/TaskView/FutureView/FutureViewTask.module.css, frontend/src/components/TaskView/FutureView/FutureViewTask.tsx
This pull request fixes a bug relating to the introduction of Canvas tasks. When the text for the task overflows, our previous placeholder icons for Canvas tasks did not properly align themselves and were shifted by the extra text. This PR introduces a better placeholder with identical attributes to the normal icons on non-Canvas tasks so that the checkboxes on the left are aligned again.
Before:
After:
Check if any of your professors added a super long Canvas assignment that causes the text to overflow the `FutureViewTask` text. See that the checkboxes on the left are now aligned, no matter how long this text is.
=> Fix Canvas task misalignment resulting from obnoxiously long titles

common/src/util/const-util.test.ts
Then we can avoid forgetting to update it until mid-semester, like #455.
The test passes. You can try to set the date to 2020/1/1 to make it fail locally.
=> Add a test to remind ourselves to update date constants

.github/workflows/ci-frontend.yml
The new action is built with TS instead of Docker container, so we can reduce some CI runtime by avoiding building a docker container
See how it deploys in a CI run.
=> Bump github-pages deployment action

deploy-functions
The firebase function doesn't seem to require it. See this sample:
https://github.com/firebase/functions-samples/blob/master/child-count/functions/package.json
SInce it causes problems in deployment: https://github.com/cornell-dti/samwise/runs/598445609, let's just remove it.
Test in staging
=> Remove main field in generated package.json for functions deployment

deploy-functions
It turns out the extra . on macOS means nothing but it means a lot on linux. See https://askubuntu.com/a/1151667
Test in staging
=> Unbreak functions deployment

.github/workflows/release-workflow.yml
Following the change in `.github/workflows/cd-workflow.yml`.
:eyes: or test in prod
=> Generate sdk from secret for production release

README.md
Today I received a random email asking me why he cannot compile samwise codebase. Then I discovered that our docs are outdated. This diff updates them to match the latest yarn workspace setup.
:eyes:
=> Fix outdated information in README

frontend/src/App.tsx, frontend/src/index.tsx, frontend/src/util/gate-keeper.ts
Out current gate keeping code works, but it's hard to switch it. You either need to memoize and type in a long, ALL_CAP string into developer console, or copy that from the source code (given that you know where it is).
Not surprisingly, this setup caused our developers (including me) becoming lazy in testing the gated code that they are not working on. This is probably what caused #483 to happen.
Instead of blaming individual developer or reviewer, let's make it easy to switch, so then there will be no excuse of not testing it thoroughly.
I added a `GateKeeper` module, which can be injected into the global scope. The injection happens in `src/index.tsx` to ensure that `GateKeeper` object with toggle methods is always available in global scope. In this way, we can easily toggle it in …
=> Setup a GateKeeper that is easier to use

frontend/src/components/TaskView/FutureView/FutureViewTask.tsx, frontend/src/components/TitleBar/Canvas/CanvasCalendar.tsx
Per Matthew's request, Canvas tasks can now be deleted after unlinking Canvas. Also added better messaging.
Linking Canvas:
Unlinking Canvas:
Task view after unlink:
=> Canvas hotfix

common/src/types/firestore-types.ts, common/src/types/store-types.ts, frontend/src/components/Util/TaskEditors/TaskEditor/NewSubTaskEditor.tsx, frontend/src/components/Util/TaskEditors/TaskEditor/index.tsx, frontend/src/firebase/actions.ts, frontend/src/firebase/listeners.ts
Added optional groupfield to onetimetask and onetimetask metadata 
Added group type to firestore-types
- Database schema change (anything that changes Firestore collection structure)
Added a samwise-groups that tracks its name : string , members : string[], and deadline: Date
=> updated firestore types for group tasks

frontend/src/util/gate-keeper.ts
We always want to reload the page once GK changes, so let's just include it in GK function call.
Try run `GateKeeper.enableGroupTask()` and `GateKeeper.disableGroupTask()`
=> Reload on GK change

frontend/src/components/TaskView/FocusView/index.tsx, frontend/src/components/TaskView/FutureView/index.tsx, frontend/src/firebase/actions.ts
The drag and drop user experience is far from being perfect.
To make order persistent, we have to save the updated order in the firestore. Although firestore seems to have ['latency compensation'](https://firebase.google.com/docs/firestore/query-data/listen#events-local-changes) that can avoid a roundtrip before updated data is pushed to remote, the listener update is still not **synchronous**, which causes a big trouble in dnd that relies an a synchronous state change.
In the past, we introduced `localTasks` as a cache in focus view to solve the problem. We are able to mostly avoid the dropped task bouncing back to the original position, but there are still some occasional flashes. In future view, such caching mechanism has not been implemented, so the resulting experience is even worse. …
=> Seamless drag-and-drop experience

common/src/firebase/database.ts, common/src/types/action-types.ts, common/src/types/firestore-types.ts, common/src/types/store-types.ts, firestore.rules, frontend/src/firebase/actions.ts, frontend/src/firebase/listeners.ts, frontend/src/store/actions.ts, frontend/src/store/reducers.ts, frontend/src/store/state.ts
Create firebase functions and add support in the Redux Store for the `samwise-group-pending-invites` collection, used to store invitations for people to join a group. 
There is now a function called `sendInvite()` that can be called to invite a user to a group.
Invitations are pulled down to the redux store of the receiving user.
Also changed Firestore security rules to match.
Manually added a document to Firestore, and then added some test code to print out `JSON.stringify(pendingInvites)` from the Redux store, and it shows up correctly:
Likewise, manually calling the function to send an invite works.
As does manually calling the function to reject an invite, though I'm not sure how to screenshot that.
=> Firestore Support for Sending Group Invitations

frontend/src/components/TitleBar/GroupInvites/index.module.css, frontend/src/components/TitleBar/GroupInvites/index.tsx, frontend/src/components/TitleBar/index.tsx, frontend/src/firebase/actions.ts
Implement basic UI to allow users to see and reject group invitations.
Can gracefully handle multiple invitations:
Disappears when all are dismissed:
Rejecting an invitation works.
First, confirm that an invitation exists in Firestore:
Then click reject:
Observe the invitation is gone:
=> View and Reject Invitations

.github/workflows/ci-frontend.yml, .github/workflows/cleanup-workflow.yml
GitHub finally supports [org-wide secrets](https://github.blog/changelog/2020-05-14-organization-secrets/). It's time to migrate away repo-specific tokens, and use the org-wide token `BOT_TOKEN` and `FIREBASE_TOKEN` instead. It makes it much easier to routinely rotate the tokens for better security.
Everything should still pass in CI
=> Standardize bot token in CI

frontend/src/components/TitleBar/Tags/TagAdder.module.css, frontend/src/index.scss
This PR fixes some style issues with our calendar date picker powered by `react-calendar`. Since the last prod release, the UI of the calendar picker has become messed up (but the functionality is still there). ~~We haven't bumped the version of `react-calendar` since,~~ (actually we have bumped react-calendar) so this is likely to have been that or due to the accessibility changes earlier in which we changed tags for buttons to `<button>`.
This issue was pointed out by @mt-xing in #516. 
**Before:**
**After**
Play with the calendar / add date feature on staging for this PR and compare to current prod (https://samwise.today/)
Only tested so far on my Windows 10 laptop running on Chrome.
=> Fix calendar styles to avoid regression

.eslintrc, frontend/src/PersonalView.tsx, frontend/src/ViewSwitcher.tsx, frontend/src/components/GroupView/MiddleBar/People/Member.tsx, frontend/src/components/GroupView/MiddleBar/People/index.tsx, frontend/src/components/GroupView/MiddleBar/TaskQueue/index.tsx, frontend/src/components/GroupView/MiddleBar/index.tsx, frontend/src/components/GroupView/RightView/GroupTaskRow/index.tsx, frontend/src/components/GroupView/RightView/index.tsx, frontend/src/components/GroupView/index.tsx, frontend/src/components/SideBar/GroupIcon.tsx, frontend/src/components/SideBar/index.tsx, frontend/src/components/TaskView/FocusView/CompletedSeparator.tsx, frontend/src/components/TaskView/FutureView/FutureViewSevenColumns.tsx, frontend/src/components/TaskView/ProgressTracker/Bear.tsx, frontend/src/components/UI/Loading.tsx, frontend/src/components/UI/ModeIndicator.tsx, frontend/src/components/Util/Modals/TextInputModal.tsx, frontend/src/components/Util/SearchBox/DropdownItem.tsx, frontend/src/components/Util/SearchBox/index.tsx, frontend/src/firebase/listeners.ts, functions/src/focus-today-task.ts, functions/src/remove-old-tasks.ts
Motivation:
Generated by `cd frontend && npx @next/codemod name-default-component`, and manually rename components that are named `Index` to be named after their parent folder.
Added a linter rule to enforce that we don't regress.
👀
=> Give all default exports a name for fast refresh

.github/workflows/tssa-analysis.yml, frontend/src/ViewSwitcher.tsx, frontend/src/components/UI/ModeIndicator.module.scss, package.json, yarn.lock
In the past, we had plenty of SEVs that is caused by some innocent looking changes that greatly messed up code elsewhere. In this diff, I propose to use `@dev-sam/tssa` to statically analyze each diff to report all files that can be potentially affected by your diffs.
Right now, tssa will perform the analysis quite naively:
1. Build a dependency graph of the entire project
2. In the CI, call `git diff` to get a list of changed files. TSSA group those changed file paths into workspaces.
3. For a TS file change, we compute its reverse dependencies and transitive reverse dependencies
4. For a css file change, we compute both its transitive forward dependencies and transitive reverse dependencies. Both directions are needed due to css' cascading nature.
Let's experiment on this to see whether …
=> Adopt tssa to statically analyze impact of each PR

common/firebase/database.ts, common/types/firestore-types.ts, frontend/src/components/Util/AppInit/LoginBarrier.tsx, frontend/src/firebase/actions.ts, frontend/src/firebase/auth-util.test.ts, frontend/src/firebase/auth-util.ts
This pull request allows for population of the `samwise-users` collection in the Firestore. Every time a user logs in, the `useEffect` hook in `LoginBarrier` calls a newly created Firebase action that adds a new document to `samwise-users` with `name` and `photoURL` fields (this can be scaled to include more fields in the future, should we want to store more about a user). This will allow for searching names along with corresponding profile photos of group members associated with emails in Group View.
If the user's name is already stored in `samwise-users`, we don't make any change to the name, but update the profile photo.
=> Store user data in Firestore upon login

.github/workflows/e2e-course-info.yml
This PR reduces the course info check frequency as suggested in #533. We no longer run course info check on push to master and instead run it every week before/at our meeting (Saturdays 3pm). 
👀 Action should no longer be triggered on push to master but it should run on Saturday 3pm EDT/19:00 UTC (if I got the cron syntax right).
=> Update course info check frequency

frontend/src/ViewSwitcher.tsx, frontend/src/components/GroupView/MiddleBar/People/Member.tsx, frontend/src/components/GroupView/MiddleBar/People/index.tsx, frontend/src/components/SideBar/AddGroupTags.tsx, frontend/src/components/SideBar/index.tsx, frontend/src/components/TaskView/FutureView/FutureViewControl.tsx, frontend/src/components/TaskView/FutureView/FutureViewTask.tsx, frontend/src/components/TaskView/FutureView/index.tsx, frontend/src/components/TitleBar/index.tsx, frontend/src/components/Util/AppInit/LoginBarrier.tsx, frontend/src/components/Util/TaskEditors/FloatingTaskEditor.tsx, frontend/src/components/Util/TaskEditors/InlineTaskEditor.tsx, frontend/src/components/Util/TaskEditors/TaskEditor/index.tsx, frontend/src/util/ga-util.ts, frontend/src/util/task-util.ts, frontend/tsconfig.json
Absolute imports can be very confusing because the starting folder sometimes shares the same with the library we are using. e.g. We have a top-level folder `firebase` in src and also `firebase` as a dependency. When we import `firebase/xyz`, it's not immediately clear whether we are importing `firebase` from a local util or from `firebase` in node_modules.
This diff removes the `baseUrl` in tsconfig.json, and use that as a guide to remove all remaining absolute imports.
Preview site loads, CI tests pass.
=> Eliminate all absolute imports

frontend/src/firebase/actions.ts
Looks like a bug when we only update photo but not username. @ptwu 
Edit your name in firestore manually in db. Refresh the page, and check firestore record updates to your google username again.
=> Auto update username when the user record already exists

frontend/src/components/Util/AppInit/LoginBarrier.tsx
Group task requires us to test interactions between users. Therefore, it's better to have two accounts using samwise at the same time. Right now we have a client only check on cornell.edu account. Since you usually don't have two cornell emails, it adds friction to testing since you need to manually enter data in the db to mock another user.
Let's remove the check for dev to unblock play-testing group tasks.
:eyes:
=> Allow cornell.edu check to be by passed during dev

common/types/firestore-types.ts, common/types/store-types.ts, frontend/src/ViewSwitcher.tsx, frontend/src/components/GroupView/RightView/index.tsx, frontend/src/components/GroupView/index.tsx, frontend/src/components/SideBar/index.tsx
We already have redux store connected to the firestore collection. Let's read from redux store to replace hardcoded data.
It is correctly rendering my test group with these info:
=> Render GroupView and SideBar using groups from firestore

common/types/store-types.ts, frontend/src/components/GroupView/MiddleBar/GroupViewMiddleBarPeopleList.tsx, frontend/src/components/GroupView/MiddleBar/index.tsx, frontend/src/components/GroupView/RightView/index.tsx, frontend/src/components/GroupView/index.tsx
This PR changes the member list from a hardcoded names to a list of profiles from firestore. I extract the logic of fetching users into a custom hook since the logic is a bit involved. See the inline comments for its flow.
To allow reading the profile from client side listeners, we do have to loosen the security rules a little bit. I currently loosen the rule to allow read if the user's email ends with @cornell.edu. I think this setup doesn't weaken any security measures. Currently it will only expose name and profile picture, which you can get by typing the email in cornell email composer anyways.
=> Render a list of user profiles in the group from firestore

course-info/run, course-info/src/fetch-exam.ts, course-info/src/merge-json.ts
This pull request uncomments the prelim parsing code, as the prelim schedule has been posted on the registrar [here
](https://registrar.cornell.edu/exams/fall-prelim-exam-schedule). The format of the exam listings has also changed, and the HTML parser has been updated accordingly as explained below.
We can't add finals, as the registrar doesn't have this data yet.
While the spring prelim schedule from SP20 is no longer accessible, I used archive.org to find a cached version of the page. Previously, dates were in the format `MM/DD/YYYY` for each class, but now they are in the format `DAY_OF_WEEK DD MONTH_NAME`. The HTML parser has been updated accordingly to create a Date object that corresponds to the new date format.
SP20
FA20
Run the bash script in `/course-info` by running `./run` in …
=> Adjust prelim and final URLs and fix parser for FA20

common/types/store-types.ts, frontend/src/components/TaskCreator/GroupMemberPicker.tsx, frontend/src/components/Util/GroupMemberListPicker/SearchGroupMember.module.scss, frontend/src/components/Util/GroupMemberListPicker/SearchGroupMember.tsx, frontend/src/components/Util/GroupMemberSearchBox/GroupMemberSearchBox.tsx
Replaces the tag picker in normal view with a group member picker when in group view. Group members can be searched by either their names or their Cornell netIDs.
=> Add search bar to assign group members

frontend/src/components/TaskCreator/DatePicker.tsx, frontend/src/components/TaskCreator/FocusPicker.tsx, frontend/src/components/TaskCreator/Picker.module.scss, frontend/src/components/TaskCreator/TagPicker.tsx, frontend/src/components/TaskCreator/__snapshots__/FocusPicker.test.tsx.snap, frontend/src/components/TaskCreator/__snapshots__/TagPicker.test.tsx.snap
Changed span tags for all the pickers to button tags. Adjusted the corresponding css to maintain the same design by adding more css classes for each picker. Each picker still performs the same as before, but internally each picker is a button now. 
Mostly changed border-color, color, background-color, and padding to get the focus picker to look like before it was changed to a button - made a new class with these attributes
Changed border-color, color, font, width and height to get the tag and date picker to look like before it was changed to a button- made a new class called "TagButton" and DateButton  to integrate these changes
Compared the original functionality from before making the changes to after making each picker a button. Original functionality/appearance: …
=> Changed FocusPicker, TagPicker, and DatePicker to buttons

frontend/src/components/TaskView/FutureView/FutureViewTask.tsx
Originally, we have the default icon next to the task title be the repeating icon, so now when we add a new type `GROUP`, it will default to the repeating icon. Let's make the Placeholder (empty) the default and if it is `ONE_TIME` and not a canvas task, we can show the `DragIcon`. All other cases, leave the icon blank.
Make group, one time, and repeating tasks and check the icons.
=> Fix group tasks icon in personal view

frontend/src/components/TaskCreator/Picker.module.scss
Changed resetButton positioning to match that of the original positioning. Also resized the tag and date picker as they were too stretched out. 
Added right and top margin to resetButton. Also adjusted the widths of the tag and date picker. 
This pull request is the first step towards implementing feature Foo
Compared functionality to original design after making changes. 
Updated: 
Original:
=> Changed resetButtonPos positioning, resized tag and date picker

frontend/src/components/Util/TagListPicker/TagListPicker.module.scss
This pull request is a 1 line fix that just makes new task class tags under tag picker have center alignment, fixing the issue pointed out by @meganyin13 in #562.
play with tagpicker :eyes:
=> Make class tags center aligned in TagPicker

frontend/src/components/GroupView/RightView/GroupTask.tsx, frontend/src/components/GroupView/RightView/GroupTaskRow.tsx, frontend/src/components/GroupView/RightView/GroupTasksContainer.tsx, frontend/src/components/GroupView/RightView/index.tsx, frontend/src/components/GroupView/index.tsx
Replace temporary data pulled from focus view with actual data from Firestore according to the group and user.
resolves #560 
Play with it on staging. 
Note: the add tasks is actually broken because it adds based on group name rather than the group id and only assigns the task to yourself. See: #567
The way I have been adding tasks is just using the add task feature at the top and editing fields manually in Firestore.
Subtasks are not yet rendered/supported until there is some util for converting the string[] from Firestore type to the Store type SubTask[]
=> GroupTasks pulling real data from Firestore

frontend/src/ViewSwitcher.tsx, frontend/src/components/GroupView/MiddleBar/GroupViewMiddleBarMemberRow.module.scss, frontend/src/components/GroupView/MiddleBar/GroupViewMiddleBarMemberRow.tsx, frontend/src/components/GroupView/MiddleBar/GroupViewMiddleBarPeopleList.tsx, frontend/src/components/GroupView/MiddleBar/ProfileImage.module.scss, frontend/src/components/GroupView/MiddleBar/ProfileImage.tsx, frontend/src/components/GroupView/MiddleBar/index.tsx, frontend/src/components/GroupView/RightView/GroupTaskRow.module.scss, frontend/src/components/GroupView/RightView/GroupTaskRow.tsx, frontend/src/components/GroupView/RightView/index.tsx, frontend/src/components/GroupView/index.tsx, frontend/src/components/SideBar/AddGroupTags.module.scss, frontend/src/components/SideBar/AddGroupTags.tsx, frontend/src/firebase/actions.ts
This pull request implements group creation, group leaving for a user's groups, and rendering profile pictures for group members in the UI. 
We create a group using the `createGroup` Firebase action in `actions.ts`, which correspond to each of the class ID picker buttons when hovering on the plus button on the left view switcher bar (this has already been implemented, but with no functionality). The default values chosen are a group `name` of `New group`, `deadline` of the current day, and `member` a singleton array of just the user who created it. For group leaving, we use the `leaveGroup` action, which is also fairly straightforward. However, we also want the page to rerender so that the group that we left is no longer displayed on the user's screen, so we need to lift state up by …
=> Connect group tasks UI to backend for creating/leaving and profile images

.github/workflows/cd-workflow.yml, .github/workflows/release-workflow.yml, firestore.rules
This PR adds deploying firestore rules as part of the CD process when we merge into staging/release. We want the [firestore.rules](https://github.com/cornell-dti/samwise/blob/master/firestore.rules) to be the single source of truth for security rules. Hopefully, this can prevent SEVs.
I think we have a dummy rule for `demo-comment-board` that I deleted. If this works, on CD it should trigger a new firestore rules deploy which we can see on the dashboard.
I got permission to steal this task from @jason-tung
=> Deploy Firestore rules

frontend/src/components/SideBar/index.module.scss
It is not used anywhere to style anything.
The only place where `styles.AddGroup` appears is here:
https://github.com/cornell-dti/samwise/blob/54876502d725903f31f4183a016714405b856034/frontend/src/components/SideBar/index.tsx#L42-L49
Which doesn't contain any child `p`.
Affected components still look fine.
=> Remove dead css code

frontend/src/components/TaskCreator/index.module.scss, frontend/src/components/Util/AppInit/Login.module.scss
Let's ensure that we only use z-index when we really need them.
Affected components look fine:
=> Eliminate z-index: 0 and z-index: -1

frontend/src/components/TitleBar/Onboarding/Onboard.module.scss
Move the css around so that we have 4 less css warnings.
dti-github bot says that there is no significant lines, which means that I just moved around some stuff 👀
=> Move ModalOptions css to eliminate 4 no-descending-specificity warnings

frontend/src/components/TaskCreator/DatePicker.tsx, frontend/src/components/TaskCreator/Picker.module.scss
The child selectors can easily cause us to miss some dead css code, like #584. This diff replaces them with a css class for each container and button, so that it's less likely for us to miss dead css. It also helps to removes some css linter warnings :)
Master:
This diff:
=> Avoid child selector for date picker save and cancel buttons

frontend/src/components/TaskCreator/DatePicker.tsx, frontend/src/components/TaskCreator/Picker.module.scss, frontend/src/components/UI/SamwiseIcon.tsx
This usage of css child selector is particularly bad. It's actually acting on the `SamwiseIcon`'s `span` container. It's bad because it assumes the implementation detail of its child component, which makes components more tightly coupled.
This diff makes `SamwiseIcon`'s span container css class overridable, so we no longer need this hack.
master:
this diff:
Q: Who created this bad css code?
A: It's me in #518. 😅
=> Avoid css child selector for Tag and Date Display component

frontend/src/components/Util/TaskEditors/TaskEditor/index.tsx
#574 only removed the save button for group task but it didn't fix the logic for autosave. This diff fixes that.
Broken on master:
Fixed in this diff:
=> Fix autosave functionality for group task

frontend/src/components/SideBar/GroupIcon.module.scss, frontend/src/components/SideBar/GroupIcon.tsx
This pull request implements group task sidebar icon colors as in the Figma design [here](https://www.figma.com/file/MoF3jQ5hQ9dT76iZ57i9VN/Group-Work?node-id=878%3A3099). Previously, groups all had the same color, but this can help users disambiguate different classes with the same subject. This required a refactor of GroupIcon to get the specific tag from the course ID from the Redux store and extract the color of the tag for it. Course IDs for Tag objects are in the form `{some number} {subject} {class number}`, but the `classCode` given to the `GroupIcon` is only `{subject} {class number}`. We split the string to compare only the subject and class number to try and match the tag to a course, and update the group icon background color accordingly.
Enable group tasks in the GateKeeper. …
=> Implement group task sidebar icon colors from course IDs

frontend/src/components/SideBar/index.module.scss, frontend/src/components/TitleBar/Settings/SettingsButton.module.scss, frontend/src/components/TitleBar/Settings/SettingsButton.tsx, frontend/src/components/TitleBar/Settings/__snapshots__/SettingsButton.test.tsx.snap, frontend/src/components/TitleBar/index.module.scss
We shouldn't do this kind of blanket button styling at all, since it affects too many buttons at once. However, we are already stuck with this for a long time and it's already affecting too many buttons. :(
This diff tries to mitigate the problem by moving two same instances of this blanket button styling into 1SettingButton.module.css`, so that this kind of bad styling practice only appears once, so it will be easier to us to fix them in the future. It also helps to remove another `no-descending-specificity` css warning.
master:
current:
=> Move blanket button styling of settings page to SettingButton css

course-info/src/fetch-exam.ts, course-info/src/merge-json.ts, course-info/src/types.ts
This PR implements the final data parser, adjusted for the FA20 semifinal schedule released today [here](https://registrar.cornell.edu/calendars-exams/semifinal-exam-schedule). It has been adapted so that it fits this semester's current layout.
Run the bash script in `/course-info` by running `./run` in the directory. See that no errors occur. You can cross-check the generated .json file to see if the examTimes field for a certain class object is defined. For example, CS 3110 has a semifinal on Nov 18 at 7:30PM, and we can cross-check the Unix time to see it is the same date.
=> Update course-info script for FA20 semifinal data

frontend/src/ViewSwitcher.tsx, frontend/src/components/GroupView/RightView/index.module.scss, frontend/src/components/GroupView/RightView/index.tsx, frontend/src/firebase/actions.ts
This diff added the support for editing group name. The [design](https://www.figma.com/file/MoF3jQ5hQ9dT76iZ57i9VN/Group-Work?node-id=878%3A820) doesn't seem to tell us how it should look, so I decided to go with the prompt modal first. We already have a prompt framework setup, so even if we don't end up using prompt for name edit, we still don't waste too many time on the UI code.
It turns out that the code for ViewSelector also needs some revision. Right now we store the entire group object in the state. This is bad because when the group from firestore changes, we will end up storing an stale value. Thus, I changed it to store selected group id instead, so that when content of the group updates (e.g. name), it will correctly trigger an rerender.
You can easily see that there is a flash …
=> Support editing group name

common/types/store-types.ts
This pull request adds semifinals as a type of exam paired with its time in the frontend so we can display it as imported exams.
:eyes:
=> Add semifinal to exam + time type in frontend 

frontend/src/components/GroupView/index.tsx
This PR fixes the issue mentioned in #593. The reason for the flash is because we are doing a bad job with caching data.
- For fetching group task, we should directly use group id as the key for `useEffect` instead of the entire object, since we only care about the stable ID, not some irrelevant changes like group name.
- For fetching group members, we need to overcome the issue of member list not changing, but a changed group object created a new member list object with the exact same content. Therefore, I joined the member email list into string to make it usable as a stable key, to prevent unnecessary updates.
no longer flashes
@jason-tung since you write the original code for fetching group tasks.
=> Better data caching for group view

frontend/src/firebase/actions.ts
This PR fixes error pointed out in this week's release #602 where semifinals were incorrectly labeled in the frontend.
Check for semifinals to show up instead of "Prelim" when importing course exams.
=> Label semifinals correctly in the frontend

frontend/src/components/UI/OverdueAlert.module.scss
This PR fixes the overdue task `!` badge to place it in the top right again. This bug is currently in prod, so we should maybe consider releasing soon.
Make a task and make it overdue. See that the warning symbol is now at the top right of the card. Check both group and personal view and see it works.
Before
After
=> Fix overdue alert style so it appears on task card

common/firebase/common-actions.ts, common/types/firestore-types.ts, common/types/store-types.ts, common/util/task-util.test.ts, frontend/src/components/GroupView/RightView/index.tsx, frontend/src/components/TaskCreator/index.tsx, frontend/src/firebase/actions.ts, frontend/src/firebase/listeners.ts, frontend/src/store/reducers.test.ts, frontend/src/store/state.ts, functions/src/iCalFunctions.ts
This pull request fixes relevant code in the frontend and in functions that considers task owners to be strings rather than string arrays. We created the script in #607 to run on all tasks in the db and change the owners to singleton string arrays instead of strings, and this corresponding PR allows for the data from the backend to be displayed correctly.
Review this PR carefully and run the script from #607. If the changes happen as expected in the Firestore, we can merge this in after. See that functionality is preserved as it was for personal view and everything.
The default value of `owner` for a task used to be the empty string `''`, but is now `['']`.
This is a breaking change as it changes the default value of owners in tasks, and how owners are handled in the frontend.
=> Fix frontend task owner code to accomodate new owner schema

package.json, yarn.lock
Adopt new tssa that gets rid of noisy css change report and make change reports more succinct.
It makes the change reports more succinct by only report direct affects if the reference tree is linear. In this case it's safe to only report the direct reference, since this is the only place we need to look into and test.
Running `git diff 0d12e77b 55e1d3ad | yarn tssa` (change in #608) gives us:
```
Your changes in `frontend/src/components/GroupView/RightView/index.tsx` will directly affect: `frontend/src/components/GroupView/index.tsx`
Your changes in `frontend/src/components/TaskCreator/index.tsx` may directly affect:
> `frontend/src/PersonalView.tsx`
> `frontend/src/components/GroupView/RightView/index.tsx`
Your changes in `frontend/src/firebase/actions.ts` may directly affect:
> …
```
=> Adopt tssa 0.0.10

common/firebase/common-actions.ts, common/types/firestore-types.ts, common/util/general-util.test.ts, firestore.rules, frontend/src/components/TaskCreator/index.tsx, frontend/src/firebase/actions.ts, frontend/src/firebase/listeners.ts
Merging in #607 and #608 and applying the Firebase function from #607 results in some issues. namely, the change to the `FirestoreCommon` type, which assumes that every firestore document now has an owner field of type `string[]`. However, this only applies to tasks - other entities will still have singular owners. As a result, subtasks and tags were not being shown.
This PR also introduces new security rules to fit the new `owner` definition for tasks, and fixes the `mergeWithOwner` function for subtasks, since subtasks still have singular owners.
See that frontend on staging should display everything as normally intended: subtasks for tasks with correct tags, group icons have the correct background colors:
=> Fix frontend to work as expected after Task owner migration

common/firebase/database.ts, common/package.json, frontend/src/firebase/listeners.ts, functions/src/iCalFunctions.ts, package.json
Setup infra for using [`FirestoreDataConverter`](https://firebase.google.com/docs/reference/js/firebase.firestore.FirestoreDataConverter) to strictify the type enforcement when we are moving between firestore data and app data. Previous, this layer is horribly `any`-typed. This diff is the first step to change that.
To avoid large disruptions, I started with an easy target: `samwise-settings`. The schema for this collection is very simple, and it's not used very often.
Go to staging to check that it still remembers that you finished onboarding tutorial, which shows that settings are not broken.
=> Setup FirestoreDataConverter for samwise-settings collection

course-info/src/fetch-exam.ts
This PR unbreaks the course exam script which was erroring on one line: CS 2800. This is because [the registrar](https://registrar.cornell.edu/calendars-exams/semifinal-exam-schedule) seems to have manually inputted this line without a hyphen in the date of the exam, which is different from the original format of each line. We hardcode the exam data for CS 2800 to avoid an error on that line.
lol
=> Unbreak course-info semifinal exam script for CS 2800

frontend/src/components/GroupView/RightView/index.tsx
We currently have a bug that let's you create a group task, but the group task just won't appear in your group view.
It's because we give an incorrect value for the `group` field in metatada. `group` should store group id instead of group name.
This diff fixes this issue.
Add a group task in group view and it should appear in your group view.
=> Unbreak group task creation

frontend/src/components/Util/TaskEditors/TaskEditor/index.module.scss
We have a regression in some release where the task tag text just got bigger. Looks to be due to [this line](https://github.com/cornell-dti/samwise/blob/68ac210a35dff04d1f89473252ff147320b19a42/frontend/src/components/Util/TaskEditors/TaskEditor/index.module.scss#L113) in TaskEditorTag introduced by #594. Not sure why it was added but removing it doesn't break anything in group/personal view and reverts the task tag to the intended size 🤷🏻‍♀️
Before:
After:
=> Fix Task Tag Text Size

common/util/datetime-util.test.ts, common/util/datetime-util.ts
It turns out that `getDateWithDateString` has never been correct. It's always slightly wrong in some weird ways. This is what happens:
https://github.com/cornell-dti/samwise/blob/72aeb1ddc75401244758d090f9c0c1f8d400807c/common/util/datetime-util.ts#L86-L97
Today is Oct 31. Assume we want to set date for a time string `'Tue Nov 03 2020'`.
When we call `date.setMonth(10)`, the following things might be happening under the hood:
1. JS figure out that we need to move one month forward.
2. However, after we move one month forward, we landed in Nov. 31, which doesn't make sense.
3. To fix this, JS turns Nov. 31 into Dec 1.
Then when we set the date, we got this epic OFF-BY-ONE-MONTH error 😱 , which is the underlying cause of #624.
This diff tries to `setDate(1)` first to avoid this kind of …
=> Unbreak getDateWithDateString to fix #624

frontend/src/components/TaskCreator/index.module.scss, frontend/src/components/TaskCreator/index.tsx
The existing code use `left: 50%; transformX: -50%` just to center the task creator 🤦 .
This is terrible and it needs to be replaced by flexbox based solutions.
personal view: still correctly centered.
group view: still correctly centered.
personal view: opened task creator looks fine.
group view: opened task creator looks fine.
Also deleted a bunch of useless jsdoc while I'm working on that file.
=> Replace css-transform hack for TaskCreator position with flexbox

frontend/src/components/GroupView/MiddleBar/GroupViewMiddleBarTaskQueue.module.scss, frontend/src/components/GroupView/MiddleBar/GroupViewMiddleBarTaskQueue.tsx, frontend/src/components/GroupView/MiddleBar/index.tsx, frontend/src/components/GroupView/index.tsx
Tasks now show up in task queue in group view. Only the tasks for the user that is logged in show up in the task queue. 
If task is deleted from task queue, task gets deleted from right side and vice-versa. Additionally, when a new task is created for a user, it automatically gets added to the task queue. 
One task assigned to the user logged in: 
No tasks assigned to logged in user: 
Many tasks assigned to user:
=> Tasks now show up in task queue in group view

frontend/src/components/TaskCreator/index.tsx
Add this helper function to be consistent when we are checking whether the task editor should be open.
Another preparation diff to fix the problem in #618.
👀
=> Unify this.state.opened and this.props.taskCreatorOpened into isOpen

frontend/src/components/Util/TaskEditors/TaskEditor/index.tsx
For TaskEditor, one time task and group task's behavior is mostly the same. Instead, only repeating task has some special behavior.
We have some code that was written in the past when there was only one time task and repeating task, so checking whether a task is a ONE_TIME task is as valid as checking whether a task is MASTER_TEMPLATE. However, since the introduction of group task, only checking for ONE_TIME task runs the danger of doing same stuff for both repeating and group task, which is wrong in most cases.
This diff replaces the remaining checks of `=== 'ONE_TIME'` into checks for  `!== 'GROUP'`. 
Creating group task, repeating task and one time tasks still work.
=> Eliminate all ONE_TIME check in task editors

frontend/src/components/Util/TaskEditors/InlineTaskEditor.tsx, frontend/src/components/Util/TaskEditors/TaskEditor/index.tsx
Looking at the English, it should be very obvious that `active` should be true when disabled is `false`. This diff fixes this mistake first. Then it turns out that one of the usage of `active` is also flipped, so this diff fixes it as well.
Auto-expanding subtask creator when hover over inline editor still works.
Not hovered:
Hovered:
=> Fix the value for active prop passed into TaskEditor and one of its usage

frontend/src/components/GroupView/RightView/GroupTaskRow.tsx
This handler is introduced in https://github.com/cornell-dti/samwise/commit/28265c512636eef6c95d838441d91d83a6011b66, when the code is still dummy and uses `div` instead of `button`. Now we switched to button so a11y should automatically work without this extra handler. This diff removes it, with a good side effect to removing another linter warning.
Try to press that button with tabbing and enter key.
=> Remove useless onKeyPress handler in GroupTaskRow

frontend/src/components/GroupView/MiddleBar/index.tsx
Not sure what the map is doing, but the logic looks very wrong. Remove this map to avoid duplicate elements.
Middle bar still works:
@IshikaJain do you know what's going on with the map? Looking at the git blame looks like you introduced this change.
=> Remove redundunt map of groupMemberProfiles

deploy-functions.js
The error log warns about deprecated node js 8 support.
Let's see whether this can help fix functions deployment
=> Use node12 for firebase functions

frontend/src/components/TaskCreator/__snapshots__/index.test.tsx.snap, frontend/src/components/TaskCreator/index.tsx
Trying to share code between the open state and close state of the TaskCreator is the root source of evil that caused the unnecessary `position: absolute` hack mentioned in #618. In the end, we did manage to share a few lines of code, but at the cost of completely unnecessary `position: absolute` hack.
This diff starts to reverse that decision. In particular, it deals with the `!isOpen` case in one place, and then make the rest of the code only worry about the `isOpen` case. It will make the flow easier to understand, and help us untangle the unnecessary dependency between these two, so that we can eventually remove the `position: absolute` hack without worrying about the `!isOpen` case.
Closed state still works:
Open state still works:
=> Do not share code between isOpen and !isOpen for TaskCreator

.github/workflows/cd-workflow.yml, .github/workflows/release-workflow.yml, functions/src/db.ts
Just remembered that we don't actually need to store credential in secrets. In the DTI hackathon project, I directly used:
https://github.com/AkashAryal/Flower/blob/98d233e60cba8be653722e99d7a5cb739b43db52/server/src/index.ts#L1-L9
and everything seems to work fine. I still leave the credential reading code so that we can still run stuff locally if we want to.
=> Use default credentials for firebase functions in prod

frontend/src/components/TaskView/FocusView/ClearFocus.tsx, frontend/src/firebase/actions.ts
This pull request fixes the clear focus functionality caused by refactoring in #635. Previously, we did not await on the asynchronous operations of iterating through the tasks and subtasks needed to be cleared from focus, and `batch.commit()` would execute while we were still adding operations to the batch. This PR ensures that these asynchronous operations are completed before committing using `Promise.all`.
Make some tasks and focus them. Complete them and see confetti. Click clear focus.
=> Update clearFocus to await on database operations to complete

functions/src/merge-task-subtask.ts
This pull request allows for the subtask -> task migration script to be run multiple times without changing the result beyond the initial execution for subtasks already in the new format. It does this by checking if a Task document has a children field that is an array, and if the array contains `string` elements, we know it must be in the old format. Otherwise, we assume it's been updated already.
Create some tasks with subtasks in the old format using `master` from 3 commits ago. Use `ts-node` to run `merge-task-subtask.ts` with env var `DEV=true`. See that the functionality is preserved. Try running the script again and nothing changes.
=> Make SubTask merge migration script idempotent

frontend/src/components/TaskView/FocusView/ClearFocus.tsx, frontend/src/components/TaskView/FutureView/FutureViewSubTask.test.tsx, frontend/src/components/TaskView/FutureView/FutureViewSubTask.tsx, frontend/src/components/TaskView/FutureView/FutureViewTask.tsx, frontend/src/firebase/actions.ts
This PR fixes an issue with subtask editing on repeated tasks as pointed out by @meganyin13 in #645. Previously, we assumed that all tasks were one time when updating subtasks, which was a naive implementation by me since updating specific subtasks and their attributes can get messy across repeating tasks and their forks, and with the refactor, we still have to consider forked tasks. 
In this PR, we bring back the `replaceDateForFork` prop into `FutureViewSubTask` since we need that data to know which task fork to update with the specific subtask change that we are currently handling. We can then fork a task with a given diff change using our updated `children` array after a subtask is updated for a repeated task that has a `replaceDateForFork`, 
Create a repeating task on staging. Add …
=> Fix forking and handle subtask updates on repeated tasks correctly post-migration

frontend/src/components/TaskView/FutureView/FutureViewSubTask.tsx
Forgot to update the `applyUpdate` function to be used for `onRemove` in `FutureViewSubTask`. This diff fixes that. Now, deleting a subtask should not remove all instances of the subtask across a template, but should fork the individual task with the deleted subtask instead.
#645 should be reviewable now after this PR.
=> Fix subtask removal in repeated tasks post-migration

frontend/src/components/TaskCreator/index.tsx
Inline the function to prepare for another diff that switch the order of input and other elements to avoid `position: absolute` hack.
Still works:
See the big-diff bot. It should report a significant line much less than diff lines, which shows that most lines are moved.
=> Inline renderOtherInfoEditor into render in TaskCreator

frontend/src/components/GroupView/groupview-sizes.scss, frontend/src/components/TaskCreator/index.module.scss, frontend/src/components/TaskView/index.module.scss, frontend/src/components/TitleBar/index.module.scss, frontend/src/layout-sizes.scss
Non-100vh is almost always bad, because it usually has some hidden assumption of screen size. This PR changes them to px.
=> Eliminate all vh that is not 100vh

frontend/src/components/TaskCreator/Picker.module.scss, frontend/src/components/TaskCreator/__snapshots__/index.test.tsx.snap, frontend/src/components/TaskCreator/index.module.scss, frontend/src/components/TaskCreator/index.tsx
After #617, #628, #630, #644, we are finally in a good position to fix the bad code in `TaskCreator`.
As a recap, the existing code is only `position: absolute` to hack code positions of varies components of `TaskCreator`, merely to overcome the difficulty to place some content before the `input` without input appearing after those content in JSX.
This PR almost completely rewrites the css related to positioning in `TaskCreator`. I also moved some jsx code around to make the layout make more sense.
Old:
New personal:
New group:
=> Avoid using position: absolute to construct TaskCreator. Close #618

frontend/src/components/TaskCreator/index.module.scss, frontend/src/components/TaskView/FutureView/FutureViewTask.tsx, frontend/src/components/TitleBar/Onboarding/Onboard.module.scss, frontend/src/components/TitleBar/Settings/SettingsPage.module.scss, frontend/src/components/Util/TaskEditors/FloatingTaskEditor.tsx
Make it consistent with the rest of the codebase. Close #432.
Before: 
After:
=> Use 840px as desktop-mobile breakpoint. Close #432

frontend/src/components/Util/TaskEditors/TaskEditor/RepeatFrequencyHeader.module.scss
Give the frequency header a constant height, so that browser can easily pre-compute the height. In this way, there will be no height discrepancy between initial render and subsequent render. This is the root cause of #652, so this PR can close #652.
No longer shifting!
=> Fix Editor shifting problem

frontend/src/components/GroupView/RightView/index.module.scss, frontend/src/components/GroupView/RightView/index.tsx
Right now in the code, we are using RightView class twice, which is incorrect and caused we to have wrong layout with regard to replacing task progress at the bottom of the screen. This PR fixes that.
=> Ensure the group task progress is always at the bottom of the screen

frontend/src/components/GroupView/MiddleBar/GroupViewMiddleBarTaskQueue.tsx
=> Fix css class typo in GroupViewMiddleBarTaskQueue

frontend/src/components/TaskView/FocusView/FocusTask.tsx, frontend/src/components/Util/TaskEditors/InlineTaskEditor.tsx, frontend/src/components/Util/TaskEditors/TaskEditor/index.tsx
Largely resulting from the changes in #635 (migration of SubTask -> Task in the types), checking off a pinned subtask in a task in focus view can delete other subtasks unintentionally. This is because since subtasks are now a part of the `Task` type, the filter between completed and uncompleted tasks in focus view actually creates two different forks of the same task. This is bad, since we apply changes through the `task-diff-reducer` using its hook which needs to have `Task` data. Also, as pointed out by Sam, since I nuked the subtask diffing functions, the task will not handle these forks correctly, and we now have unexpected behavior.
This issue was pointed out by Michael @mt-xing in #679 (with screenshots on how to reproduce on `master` atm), and this PR aims to fix it.
In order to …
=> Fix Focus View Filtered Subtasks SEV

frontend/src/components/GroupView/RightView/index.tsx, frontend/src/components/TaskCreator/index.tsx
This pull request fixes `TaskCreator` bugs.
`TaskCreator` now closes correctly.
Manual member assignment takes precedence.
=> Fix TaskCreator and member assignment bugs

frontend/src/components/GroupView/RightView/CompletedTasks/CompletedTask.tsx, frontend/src/components/GroupView/RightView/CompletedTasks/CompletedTasks.module.scss, frontend/src/components/GroupView/RightView/GroupTask.module.scss, frontend/src/components/GroupView/RightView/GroupTaskRow.module.scss, frontend/src/components/GroupView/RightView/GroupTasksContainer.module.scss, frontend/src/components/GroupView/groupview-sizes.scss
Right now the group view components didn't align so well and look messy. This diff tidy them up by making them more aligned.
Design:
Before:
After:
=> Fix group view css to make things more tidy and aligned

frontend/src/PersonalView.tsx, frontend/src/components/GroupView/MiddleBar/GroupViewMiddleBarMemberRow.tsx, frontend/src/components/GroupView/RightView/index.tsx, frontend/src/components/GroupView/index.tsx, frontend/src/components/TaskCreator/index.test.tsx, frontend/src/components/TaskCreator/index.tsx
Currently, the right view in group view is communicating with TaskCreator by some ad hoc local state. Now if we want to add another similar communication for the purpose of implementing the + button in MiddleView, we need to duplicate the logic, which is bad.
It turns out that we can use React context to lift the state up, and use hooks to _reactively_ communicate with each other. This PR refactors the existing code to use hooks instead, and use the new setup to quickly implement the functionality for the assign button in the MiddleBar.
- Try opening and closing task creator both in personal and group view.
- Try to click the assign button in both MiddleBar and RightView
=> Make assign button (+) in the middle bar work

functions/src/send-email.ts
It looks more professional, and emails are sent by sendgrid anyways.
👀
=> Use DTI email as sender for group task reminder emails

frontend/src/components/GroupView/RightView/GroupTask.module.scss
Current implementation doesn't take the margin in the child component into account, so things are squzzed.
(See jason's last task in the screenshot)
Fixed:
=> Take the margin width into account to fix group task squzzed problem

frontend/src/components/GroupView/RightView/GroupTaskRow.module.scss
Credit: https://stackoverflow.com/questions/32689686/overlapping-css-flexbox-items-in-safari
Before:
After:
=> Add flex-shrink to group task row to unbreak group task in safari

frontend/src/components/TaskView/FutureView/FutureViewTask.tsx, frontend/src/components/Util/TaskEditors/FloatingTaskEditor.tsx
Fixed error where floating task editor changes position when dragging focusviewtask. Now, one can only moving the focusview task when the floatingtaskeditor is closed.
=> Make focus view task draggable only when floatingtask editor isn't open

frontend/src/components/UI/OverdueAlert.module.scss, frontend/src/components/Util/TaskEditors/TaskEditor/EditorHeader.tsx, frontend/src/components/Util/TaskEditors/TaskEditor/index.tsx
This pull request fixes the extra space caused by the overdue alert after a quick and dirty fix in #605.
=> Fix overdue alert to use absolute positioning once again

frontend/src/components/GroupView/MiddleBar/GroupViewMiddleBarPeopleList.module.scss
Leave group gets pushed off screen if there are too many elements in the MiddleBar. This PR adds `bottom: 0` to pin it to the bottom of the MiddleBar.
=> Make leave group pinned to bottom of the screen

frontend/src/components/GroupView/MiddleBar/GroupViewMiddleBarTaskQueue.tsx
When you have 0 tasks in your Group View Task Queue there is a button to Add Task. This adds functionality to open up the TaskCreator when you click that button.
Empty your task queue. Click Add Task in Task Queue and make a task.
=> Empty Task Queue Add Task

frontend/src/App.module.scss, frontend/src/ViewSwitcher.tsx
In anticipation of our soon launch, we still want mobile to be usable. To do this, we just remove the group tasks feature on mobile devices :( since we have no mobile designs.
Before:
After:
=> Fix mobile view to be usable after group tasks launch

frontend/src/components/TaskView/FutureView/FutureViewTask.tsx
We are forking it rn because we are treating it like repeating task due to this check. This PR fixes it
👀
=> Do not fork group task in future view

frontend/src/components/TaskCreator/GroupMemberPicker.tsx, frontend/src/components/TaskCreator/index.tsx, frontend/src/components/Util/GroupMemberListPicker/SearchGroupMember.tsx
Fixes bugs relating to the assign to button in TaskCreator.
Tested through frontend in GroupView.
=> Let cancel button close searchbox

frontend/src/components/SideBar/AddGroupTags.tsx, frontend/src/components/SideBar/index.module.scss, frontend/src/components/SideBar/index.tsx
Right now the settings launched from sidebar is broken:
For reference, the settings launched from personal view is fine:
This PR fixes the problem that the left text is not shown. It is caused by some style being cascading down. This bug shows again that we should really avoid all those css blanketly targeting one type of html tag.
Shown now:
=> Unbreak the left text in settings launched from sidebar

frontend/src/components/SideBar/GroupIcon.module.scss, frontend/src/components/SideBar/GroupIcon.tsx, frontend/src/components/SideBar/index.module.scss, frontend/src/components/SideBar/index.tsx, frontend/src/components/TitleBar/Settings/SettingsButton.tsx, frontend/src/components/TitleBar/Settings/__snapshots__/SettingsButton.test.tsx.snap
As you can see in #707, all the buttons in the settings view is also broken. This PR fixes them in the same way: avoiding unpredictable cascades by explicitly applying css classes to the ones we want to style.
Compared to staging, sidebar doesn't change
Settings is fixed:
=> Unbreak buttons in settings view launched from sidebar

frontend/src/components/TaskCreator/DatePicker.tsx, frontend/src/components/TaskCreator/Picker.module.scss, package.json
Remove the last 2 `no-descending-specificity` warnings by replacing the implicit button styling with explicit classnames.
We now eliminated all `no-descending-specificity` warnings, so we can finally convert the warning into error!
the css is still being correctly applied:
=> Eliminate all stylelint css warnings

frontend/src/components/SideBar/AddGroupTags.module.scss
Missed this button when doing #708.
Broken:
Fixed:
=> Unbreak add group tags selector

common/firebase/common-actions.ts, frontend/src/firebase/actions.ts
Move the code there so that it can be used by both frontend and functions code. Most of the change is just moving around code.
Check creating, editing task, especially with forked ones, still works.
=> Refactor task related firestore actions into common package

common/firebase/database.ts
Currently, the functions code is failing, because the runtime type checking asserts the field is an instance of `firestore.Timestamp`. However, this class is frontend only and in functions it's using another class. Unfortunately, there is no easy way to make frontend and backend share these runtime type checking code, so I decide to loosen it to `any`, so that at least functions don't break.
No more runtime `firestore.Timestamp` instanceof check, so functions should stop failing.
=> Loosen firestore DataConverter runtime type checking with timestamp

common/firebase/common-actions.ts, frontend/src/firebase/actions.ts
Currently, when you click clear focus on a set of completed tasks, it actually appears to remove those tasks from the UI. By inspection, it's because these lines should be an `update` rather than a `set` since `set` will set the whole document to just those children.
https://user-images.githubusercontent.com/20008134/103161338-4c01cc80-47ae-11eb-8fb7-5d7565586334.mov
Create some tasks, complete them,
and then click clear focus.
I'll move this into `common/firebase/common-actions.ts` once #719 is merged.
=> Fix clear focus

common/firebase/common-actions.ts, frontend/src/firebase/actions.ts
These actions should be able to be called on functions, which doesn't have a redux store.
Therefore, I make the common actions to take full task as parameters instead of task id. Then in the frontend actions, I pass in the task fetched from redux store.
The methods refactored in this diff is important to implement #333.
Check task editing and forking still works.
=> Remove dependencence on store store in firestore common actions

frontend/package.json, frontend/src/components/GroupView/MiddleBar/ProfileImage.tsx, frontend/src/components/GroupView/RightView/GroupTaskProgress.tsx, frontend/src/components/Popup/AllComplete/index.tsx, frontend/src/components/SideBar/GroupIcon.tsx, frontend/src/components/TaskCreator/DatePicker.tsx, frontend/src/components/TaskCreator/FocusPicker.tsx, frontend/src/components/TaskCreator/GroupMemberPicker.tsx, frontend/src/components/TaskCreator/TagPicker.tsx, frontend/src/components/TaskCreator/__snapshots__/index.test.tsx.snap, frontend/src/components/TaskCreator/index.tsx, frontend/src/components/TaskView/FocusView/CompletedSeparator.tsx, frontend/src/components/TaskView/FutureView/FutureViewControl.tsx, frontend/src/components/TaskView/FutureView/FutureViewDay.tsx, frontend/src/components/TaskView/ProgressTracker/index.tsx, frontend/src/components/TitleBar/Settings/SettingsButton.tsx, frontend/src/components/TitleBar/Settings/SettingsPage.tsx, frontend/src/components/TitleBar/Settings/__snapshots__/SettingsButton.test.tsx.snap, frontend/src/components/TitleBar/Tags/ClassTagAdder.tsx, frontend/src/components/TitleBar/Tags/OtherTagAdder.tsx, frontend/src/components/UI/CheckBox.tsx, frontend/src/components/UI/SamwiseIcon.tsx, frontend/src/components/UI/SquareIconToggle.tsx, frontend/src/components/Util/Modals/TextInputModal.tsx, frontend/src/components/Util/TaskEditors/TaskEditor/EditorHeader.tsx, frontend/src/components/Util/TaskEditors/TaskEditor/index.tsx, yarn.lock
Using template literals can concat css well sometimes, but when there are conditional css classnames, it gets messy very quickly. This PR replaces those template literal css classnames with the `clsx` library, which can handle the conditional css very well.
Check the affected components' css is still fine. Read the changes to convince yourself that it's correct.
=> Use clsx to concat (sometimes conditional) css classnames

common/firebase/common-actions.ts, frontend/src/firebase/actions.ts, functions/src/focus-today-task.ts
Close #333, our last open issue.
Implemented via a firebase function that auto focuses the repeating task by forking it. It reuses the existing common util function to tell whether today is on the repeating tasks' repetition schedule.
I created a repeating task that repeats on today, and run the function manually. It indeed got focused.
=> Auto-focus repeating task by firebase functions

course-info/src/fetch-exam.ts, course-info/src/main.ts, course-info/src/merge-json.ts
This PR updates the course data and exams to Spring 2021. It also removes semifinals from consideration as the registrar is likely never implementing these again since they were a "disaster".
Run `yarn workspace course-info fetch` to grab the latest course data for SP21. CS 4670 has a prelim on Apr 6, as seen above in the corresponding Unix timestamp.
Still not updated for finals this sem since the registrar still hasn't released this info. Will submit a PR when this comes out.
=> [chore] Update course-info fetch script for SP21 and eliminate semifinals

common/util/order-util.ts
Resolve #733.
The input `originalList` contains both completed and uncompleted task. However, if a task is partially completed (i.e. with some completed subtask), it will appear twice, thus causing the duplicate order error while there should be none.
We should enforce no duplicate order by logic and test (which we already do, hopefully), instead of this buggy checker. Therefore, I just removed the checker.
Repeats steps in #733 to ensure that it no longer errors.
=> Remove testOrderUnique check in reorder function
